const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '..', 'src', 'locales');

const tr = {
  "nav": {
    "core": "Ana",
    "operations": "Operasyonlar",
    "administration": "Yönetim",
    "dashboard": "Gösterge Paneli",
    "projects": "Projelerimiz",
    "proposals": "Başvurular",
    "staff": "Personel",
    "allocations": "Tahsisler",
    "timesheets": "Zaman Çizelgeleri",
    "absences": "İzinler",
    "financials": "Finans",
    "timeline": "Zaman Çizelgesi",
    "reports": "Raporlar",
    "import": "İçe Aktar",
    "auditLog": "Denetim Kaydı",
    "collaboration": "İş Birliği",
    "settings": "Ayarlar",
    "projectOverview": "Proje Genel Bakış",
    "help": "Yardım ve SSS"
  },
  "common": {
    "save": "Kaydet",
    "cancel": "İptal",
    "delete": "Sil",
    "edit": "Düzenle",
    "create": "Oluştur",
    "add": "Ekle",
    "remove": "Kaldır",
    "close": "Kapat",
    "confirm": "Onayla",
    "back": "Geri",
    "next": "İleri",
    "search": "Ara",
    "filter": "Filtrele",
    "export": "Dışa Aktar",
    "loading": "Yükleniyor...",
    "saving": "Kaydediliyor...",
    "deleting": "Siliniyor...",
    "noResults": "Sonuç bulunamadı",
    "error": "Hata",
    "success": "Başarılı",
    "warning": "Uyarı",
    "actions": "İşlemler",
    "status": "Durum",
    "name": "Ad",
    "email": "E-posta",
    "role": "Rol",
    "date": "Tarih",
    "type": "Tür",
    "description": "Açıklama",
    "notes": "Notlar",
    "total": "Toplam",
    "active": "Aktif",
    "inactive": "Pasif",
    "all": "Tümü",
    "yes": "Evet",
    "no": "Hayır",
    "or": "veya",
    "and": "ve",
    "of": "arasından",
    "to": "hedef",
    "from": "kaynak",
    "submit": "Gönder",
    "approve": "Onayla",
    "reject": "Reddet",
    "pending": "Beklemede",
    "approved": "Onaylandı",
    "rejected": "Reddedildi",
    "download": "İndir",
    "upload": "Yükle",
    "refresh": "Yenile",
    "reset": "Sıfırla",
    "selectAll": "Tümünü seç",
    "deselectAll": "Tüm seçimi kaldır",
    "showing": "Gösterilen",
    "items": "öğe",
    "page": "Sayfa",
    "previous": "Önceki",
    "rows": "satır",
    "columns": "Sütunlar",
    "viewAll": "Tümünü gör",
    "learnMore": "Daha fazla bilgi",
    "required": "Zorunlu",
    "optional": "İsteğe bağlı",
    "synced": "Senkronize",
    "upToDate": "Güncel",
    "syncing": "Senkronize ediliyor...",
    "computing": "Hesaplanıyor...",
    "adding": "Ekleniyor...",
    "updating": "Güncelleniyor...",
    "project": "Proje",
    "projects": "projeler",
    "budget": "Bütçe",
    "actual": "Gerçekleşen",
    "remaining": "Kalan",
    "over": "Aşım",
    "period": "Dönem",
    "title": "Başlık",
    "acronym": "Kısaltma",
    "scheme": "Program",
    "lead": "Sorumlu",
    "programme": "Program",
    "partners": "Ortaklar",
    "searchPlaceholder": "Kısaltma veya başlık ile ara...",
    "noProjectsFound": "Proje bulunamadı",
    "tryAdjusting": "Aramanızı değiştirmeyi deneyin.",
    "createFirstProject": "Başlamak için ilk projenizi oluşturun.",
    "showingCount": "{{count}} proje gösteriliyor",
    "deleteProject": "Projeyi Sil",
    "deleteProjectConfirm": "\"{{name}}\" projesini silmek istediğinizden emin misiniz? İlişkili tüm iş paketleri, tahsisler ve zaman çizelgeleri de silinecektir.",
    "deleted": "Silindi",
    "hasBeenRemoved": "{{name}} kaldırıldı.",
    "failedToDelete": "Silme başarısız",
    "failedToSave": "Kaydetme başarısız",
    "suspended": "Askıda",
    "upcoming": "Yaklaşan",
    "none": "Yok",
    "member": "Üye",
    "person": "Kişi",
    "amount": "Tutar",
    "vendor": "Tedarikçi",
    "reference": "Referans",
    "category": "Kategori",
    "update": "Güncelle",
    "record": "Kaydet",
    "invited": "Davet Edildi",
    "account": "Hesap",
    "overBudget": "Bütçe aşımı",
    "noneSelected": "— Yok —",
    "ref": "Ref: {{ref}}",
    "countItems": "{{count}} {{item}}",
    "allCategories": "Tüm Kategoriler",
    "exportPdf": "PDF Dışa Aktar"
  },
  "auth": {
    "login": "Giriş Yap",
    "logout": "Çıkış Yap",
    "signUp": "Kayıt Ol",
    "signIn": "Giriş Yap",
    "forgotPassword": "Şifrenizi mi unuttunuz?",
    "resetPassword": "Şifreyi Sıfırla",
    "setNewPassword": "Yeni şifre belirle",
    "email": "E-posta",
    "password": "Şifre",
    "confirmPassword": "Şifreyi Onayla",
    "firstName": "Ad",
    "lastName": "Soyad",
    "rememberMe": "Oturumu açık tut",
    "createAccount": "Hesabınızı oluşturun",
    "alreadyHaveAccount": "Zaten bir hesabınız var mı?",
    "dontHaveAccount": "Hesabınız yok mu?",
    "termsAgree": "Tıklayarak aşağıdaki koşulları okuduğunuzu ve kabul ettiğinizi onaylarsınız:",
    "termsOfUse": "Kullanım Koşulları",
    "privacyPolicy": "Gizlilik Politikası",
    "startTrial": "14 gün ücretsiz deneyin",
    "noPaymentRequired": "Ödeme bilgisi gerekmez",
    "startUsingImmediately": "GrantLume'u hemen kullanmaya başlayın",
    "noInstallation": "Kurulum gerekmez",
    "cloudBased": "Bulut tabanlı — tarayıcınızda çalışır",
    "trialAutoEnds": "14 günlük deneme süresi otomatik olarak sona erer",
    "noObligations": "Yükümlülük yok, istediğiniz zaman iptal edin",
    "registerFree": "Ücretsiz kayıt olun",
    "startFreeTrial": "14 günlük ücretsiz denemenizi başlatın — kredi kartı gerekmez",
    "creatingAccount": "Hesap oluşturuluyor...",
    "checkYourEmail": "E-postanızı kontrol edin",
    "confirmationSent": "Şu adrese bir onay bağlantısı gönderdik:",
    "clickToActivate": "Hesabınızı etkinleştirmek ve 14 günlük ücretsiz denemenizi başlatmak için bağlantıya tıklayın.",
    "didntReceive": "E-posta almadınız mı? Spam klasörünüzü kontrol edin veya birkaç dakika bekleyin.",
    "resendConfirmation": "Onay e-postasını yeniden gönder",
    "goToLogin": "Girişe git",
    "passwordStrength": "Şifre gücü",
    "weak": "Zayıf",
    "fair": "Orta",
    "good": "İyi",
    "strong": "Güçlü",
    "passwordsDoNotMatch": "Şifreler uyuşmuyor",
    "accountRecovery": "Hesap kurtarma",
    "wellHelpYouBack": "Hesabınıza yeniden erişmenize yardımcı olacağız",
    "sendResetLink": "Sıfırlama bağlantısı gönder",
    "sendingResetLink": "Gönderiliyor...",
    "resetLinkSent": "E-postanızı kontrol edin",
    "resetLinkSentDesc": "Bu e-posta için bir hesap varsa, şifre sıfırlama bağlantısı alacaksınız.",
    "backToLogin": "Girişe dön",
    "chooseStrongPassword": "Güçlü ve benzersiz bir şifre seçin",
    "newPassword": "Yeni Şifre",
    "updatePassword": "Şifreyi güncelle",
    "updatingPassword": "Güncelleniyor...",
    "passwordUpdated": "Şifre güncellendi",
    "canNowSignIn": "Artık yeni şifrenizle giriş yapabilirsiniz",
    "securityCheck": "Güvenlik Kontrolü",
    "solveToProve": "İnsan olduğunuzu kanıtlamak için bunu çözün",
    "tooManyAttempts": "Çok fazla başarısız deneme. Daha sonra tekrar deneyin."
  },
  "callback": {
    "verifying": "Doğrulanıyor...",
    "pleaseWait": "Hesabınızı onaylarken lütfen bekleyin",
    "emailConfirmed": "E-posta onaylandı!",
    "accountVerified": "Hesabınız başarıyla doğrulandı. Kuruluşunuzu oluşturmaya ve hibelerinizi yönetmeye hazırsınız.",
    "whatsNext": "Sırada ne var?",
    "step1": "Kuruluşunuzu oluşturun",
    "step2": "İlk projenizi ekleyin",
    "step3": "Ekip üyelerinizi davet edin",
    "continueToSetup": "Kuruluma devam et",
    "youreAllSet": "Her şey hazır!",
    "verifiedRedirecting": "Doğrulandı! Yönlendiriliyor...",
    "verificationFailed": "Doğrulama başarısız",
    "linkExpired": "E-postanız doğrulanamadı. Bağlantı süresi dolmuş veya daha önce kullanılmış olabilir. Lütfen giriş yapmayı deneyin."
  },
  "dashboard": {
    "title": "Gösterge Paneli",
    "welcome": "Tekrar hoş geldiniz",
    "overview": "Genel Bakış",
    "activeProjects": "Aktif Projeler",
    "totalStaff": "Toplam Personel",
    "pendingTimesheets": "Bekleyen Zaman Çizelgeleri",
    "upcomingDeadlines": "Yaklaşan Son Tarihler",
    "recentActivity": "Son Etkinlik",
    "quickActions": "Hızlı İşlemler",
    "budgetOverview": "Bütçe Genel Bakış",
    "projectStatus": "Proje Durumu",
    "portfolioOverview": "Portföy genel bakış — {{year}}",
    "kpiProjects": "Projeler",
    "kpiStaff": "Personel",
    "kpiTotalBudget": "Toplam Bütçe",
    "kpiPersonMonths": "Kişi-Ay",
    "kpiProposals": "Başvurular",
    "kpiCollaborations": "İş Birlikleri",
    "activeCount": "{{count}} aktif",
    "submittedCount": "{{count}} gönderildi",
    "acrossAllProjects": "tüm projeler genelinde",
    "actualIn": "{{year}} gerçekleşen",
    "plannedIn": "{{year}} planlanan",
    "projectsEndingSoon": "{{count}} proje yakında bitiyor: {{names}}",
    "staffOverAllocated": "Bu yıl {{count}} personel aşırı tahsisli",
    "monthlyAllocations": "Aylık Tahsisler (KA)",
    "projectStatusDistribution": "Proje Durum Dağılımı",
    "noProjectsYet": "Henüz proje yok",
    "projectsOverview": "Proje Genel Bakış",
    "pmsYear": "KA ({{year}})"
  },
  "projects": {
    "title": "Projelerimiz",
    "description": "Kuruluşunuzun her projedeki payı",
    "newProject": "Yeni Proje",
    "editProject": "Projeyi Düzenle",
    "importWithAI": "Yapay Zeka ile İçe Aktar",
    "projectDetails": "Proje Detayları",
    "acronym": "Kısaltma",
    "fullTitle": "Tam Başlık",
    "startDate": "Başlangıç Tarihi",
    "endDate": "Bitiş Tarihi",
    "fundingScheme": "Fonlama Programı",
    "budget": "Bütçe",
    "responsiblePerson": "Sorumlu Kişi",
    "workPackages": "İş Paketleri",
    "deliverables": "Çıktılar",
    "milestones": "Kilometre Taşları",
    "personnel": "Personel",
    "documents": "Belgeler",
    "expenses": "Giderler",
    "noProjects": "Henüz proje yok",
    "noProjectsDesc": "Başlamak için ilk projenizi oluşturun.",
    "status": "Durum",
    "active": "Aktif",
    "completed": "Tamamlandı",
    "preparation": "Hazırlık Aşamasında",
    "pmRate": "KA Oranı",
    "totalBudget": "Toplam Bütçe",
    "spentBudget": "Harcanan",
    "remainingBudget": "Kalan",
    "collaboration": "İş Birliği",
    "collaborationProjects": "İş Birliği Projeleri",
    "notFound": "Proje Bulunamadı",
    "backToProjects": "Projelere Dön",
    "overview": "Genel Bakış",
    "reporting": "Raporlama",
    "grantNumber": "Hibe Numarası",
    "ledByOurOrg": "Kuruluşumuz Tarafından Yönetilen",
    "budgetBreakdown": "Bütçe Dağılımı",
    "travel": "Seyahat",
    "subcontracting": "Alt Yüklenici",
    "other": "Diğer",
    "otherDirectCosts": "Diğer Doğrudan Maliyetler",
    "indirectCosts": "Dolaylı Maliyetler",
    "overheadRate": "Genel Gider Oranı",
    "ourPmRate": "Bizim KA Oranımız",
    "personMonthsPerYear": "Yıllık Kişi-Ay",
    "totalAcrossYears": "Tüm yıllar toplamı",
    "assignedToWPs": "İP'lere atanan",
    "ofBudget": "bütçenin",
    "allocated": "Tahsis Edilen",
    "peopleAllocated": "Projeye tahsis edilen kişiler",
    "remaining": "Kalan",
    "budgetMinusAllocated": "Bütçe eksi tahsis edilen",
    "projectBudget": "Proje Bütçesi",
    "pmBudgetDistribution": "KA Bütçe Dağılımı",
    "unassigned": "Atanmamış",
    "addWorkPackage": "İş Paketi Ekle",
    "wpNumber": "İP #",
    "wpName": "Ad",
    "wpDescription": "Açıklama",
    "startMonth": "Başlangıç Ayı",
    "endMonth": "Bitiş Ayı",
    "addWP": "İP Ekle",
    "wpAdded": "İş paketi eklendi",
    "wpDeleted": "İş paketi silindi",
    "wpUpdated": "İş paketi güncellendi.",
    "deleteWP": "İş Paketini Sil",
    "deleteWPConfirm": "\"{{name}}\" iş paketini silmek istediğinizden emin misiniz?",
    "budgetPM": "Bütçe KA",
    "savePmBudgets": "KA Bütçelerini Kaydet",
    "pmBudgetsUpdated": "KA bütçeleri güncellendi.",
    "wpPmBudgetsUpdated": "İP KA bütçeleri güncellendi.",
    "projectDuration": "Proje süresi: {{months}} ay ({{start}} – {{end}})"
  },
  "expenses": {
    "title": "Giderler",
    "recordExpense": "Gider Kaydet",
    "editExpense": "Gideri Düzenle",
    "deleteExpense": "Gideri Sil",
    "deleteExpenseConfirm": "\"{{name}}\" ({{amount}}) silinsin mi?",
    "expenseRecorded": "Gider kaydedildi",
    "expenseUpdated": "Gider güncellendi",
    "expenseDeleted": "Gider silindi",
    "invalidAmount": "Geçersiz tutar",
    "noExpenses": "Kayıtlı gider yok",
    "noExpensesDesc": "Seyahat, alt yüklenici ve diğer maliyet kategorilerindeki bütçe tüketimini takip etmek için proje giderlerini kaydedin.",
    "spent": "Harcanan",
    "budgetForCategory": "{{category}} bütçesi:",
    "afterThisExpense": "Bu giderden sonra:",
    "remainingAfter": "{{amount}} kalan",
    "overBudgetAfter": "{{amount}} bütçe aşımı",
    "budgetAlertMessage": "{{category}} bütçesi %{{spentPct}} tüketildi ancak proje süresinin yalnızca %{{timelinePct}}'i geçti.",
    "descriptionPlaceholder": "Örn. Brüksel'e konsorsiyum toplantısı uçuşu",
    "vendorPlaceholder": "Örn. THY, Brüksel Oteli",
    "referencePlaceholder": "Örn. FAT-2026-001",
    "additionalDetails": "Ek detaylar...",
    "vendorPayee": "Tedarikçi / Alacaklı",
    "referenceInvoice": "Referans / Fatura No",
    "expenseCount": "{{count}} gider",
    "expenseCountPlural": "{{count}} gider"
  },
  "deliverables": {
    "title": "Çıktılar",
    "addDeliverable": "Çıktı Ekle",
    "editDeliverable": "Çıktıyı Düzenle",
    "deleteDeliverable": "Çıktıyı Sil",
    "deleteDeliverableConfirm": "\"{{name}}\" çıktısı silinsin mi?",
    "deliverableAdded": "Çıktı eklendi",
    "deliverableUpdated": "Çıktı güncellendi",
    "deliverableDeleted": "Çıktı silindi",
    "noDeliverables": "Çıktı yok",
    "noDeliverablesDesc": "Sonuçları ve son tarihleri takip etmek için proje çıktıları ekleyin.",
    "number": "Numara",
    "dueMonth": "Teslim Ayı",
    "workPackage": "İş Paketi",
    "addMilestone": "Kilometre Taşı Ekle",
    "editMilestone": "Kilometre Taşını Düzenle",
    "deleteMilestone": "Kilometre Taşını Sil",
    "deleteMilestoneConfirm": "\"{{name}}\" kilometre taşı silinsin mi?",
    "milestoneAdded": "Kilometre taşı eklendi",
    "milestoneUpdated": "Kilometre taşı güncellendi",
    "milestoneDeleted": "Kilometre taşı silindi",
    "noMilestones": "Kilometre taşı yok",
    "noMilestonesDesc": "Önemli başarıları takip etmek için proje kilometre taşları ekleyin.",
    "verificationMeans": "Doğrulama Araçları"
  },
  "reporting": {
    "title": "Raporlama Dönemleri",
    "addPeriod": "Dönem Ekle",
    "editPeriod": "Dönemi Düzenle",
    "deletePeriod": "Dönemi Sil",
    "deletePeriodConfirm": "Raporlama dönemi #{{number}} silinsin mi?",
    "periodAdded": "Raporlama dönemi eklendi",
    "periodUpdated": "Raporlama dönemi güncellendi",
    "periodDeleted": "Raporlama dönemi silindi",
    "noPeriods": "Raporlama dönemi yok",
    "noPeriodsDesc": "İnceleme son tarihlerini takip etmek için raporlama dönemleri ekleyin.",
    "periodNumber": "Dönem #",
    "technicalReportDue": "Teknik Rapor Son Tarihi",
    "financialReportDue": "Mali Rapor Son Tarihi"
  },
  "budgetChart": {
    "title": "Bütçe Tüketimi",
    "budgeted": "Bütçelenen",
    "actual": "Gerçekleşen",
    "percentUsed": "%{{percent}} kullanıldı",
    "noData": "Bu proje için bütçe verisi mevcut değil.",
    "timeElapsed": "Proje süresinin %{{percent}}'i geçti",
    "overSpending": "Harcamalar takvimin önünde",
    "underSpending": "Harcamalar planladığı gibi",
    "categories": {
      "personnel": "Personel",
      "travel": "Seyahat",
      "subcontracting": "Alt Yüklenici",
      "other": "Diğer",
      "indirect": "Dolaylı"
    }
  },
  "staff": {
    "title": "Personel",
    "addPerson": "Yeni Kişi Ekle",
    "editPerson": "Kişiyi Düzenle",
    "fullName": "Tam Ad",
    "department": "Departman",
    "role": "Rol",
    "employmentType": "İstihdam Türü",
    "fte": "TAM",
    "startDate": "Başlangıç Tarihi",
    "endDate": "Bitiş Tarihi",
    "salary": "Yıllık Maaş",
    "vacationDays": "İzin Günleri",
    "country": "Ülke",
    "isActive": "Aktif",
    "noStaff": "Henüz personel yok",
    "noStaffDesc": "Başlamak için ilk ekip üyenizi ekleyin.",
    "inviteToSystem": "GrantLume'a Davet Et",
    "accountStatus": "Hesap Durumu",
    "sendInvitation": "Davet Gönder",
    "resendInvitation": "Daveti Yeniden Gönder",
    "personCreated": "Kişi oluşturuldu",
    "personUpdated": "Kişi güncellendi",
    "personDeleted": "Kişi silindi",
    "deletePerson": "Kişiyi Sil",
    "deletePersonConfirm": "\"{{name}}\" kişisini silmek istediğinizden emin misiniz?",
    "searchPlaceholder": "Personel ara...",
    "leaveBalance": "İzin Bakiyesi",
    "leaveUsed": "{{used}} / {{total}} gün kullanıldı",
    "overheadRate": "Genel Gider Oranı",
    "phone": "Telefon",
    "avatar": "Avatar",
    "uploadAvatar": "Avatar Yükle",
    "removeAvatar": "Avatarı Kaldır",
    "personalInfo": "Kişisel Bilgiler",
    "employmentDetails": "İstihdam Detayları",
    "financialInfo": "Mali Bilgiler",
    "invitationSent": "Davet gönderildi",
    "invitationResent": "Davet yeniden gönderildi",
    "invitingUser": "Davet ediliyor...",
    "systemRole": "Sistem Rolü",
    "projectsInvolved": "Dahil Olunan Projeler"
  },
  "allocations": {
    "title": "Tahsisler",
    "description": "Projeler arası kişi-ay tahsislerini yönetin",
    "personMonth": "Kişi-Ay",
    "personMonths": "Kişi-Ay",
    "pm": "KA",
    "capacity": "Kapasite",
    "overAllocated": "Aşırı tahsisli",
    "unsavedChanges": "Kaydedilmemiş değişiklikler",
    "pmBudgets": "KA Bütçeleri",
    "bulkFill": "Toplu Doldur",
    "addRow": "Satır Ekle",
    "undo": "Geri Al",
    "redo": "Yinele",
    "allocationGrid": "Tahsis Tablosu",
    "personnelOverview": "Personel Genel Bakış",
    "projectOverview": "Proje Genel Bakış",
    "periodLocks": "Dönem Kilitleri",
    "saved": "Tahsisler kaydedildi",
    "selectPerson": "Kişi seçin",
    "selectProject": "Proje seçin",
    "selectWorkPackage": "İş paketi seçin"
  },
  "timesheets": {
    "title": "Zaman Çizelgeleri",
    "myTimesheet": "Zaman Çizelgem",
    "allTimesheets": "Tüm Zaman Çizelgeleri",
    "submitTimesheet": "Zaman Çizelgesi Gönder",
    "approveTimesheets": "Zaman Çizelgelerini Onayla",
    "hours": "Saat",
    "totalHours": "Toplam Saat",
    "period": "Dönem",
    "submitted": "Gönderildi",
    "draft": "Taslak",
    "noEntries": "Henüz kayıt yok",
    "noEntriesDesc": "Bu dönem için çalışma saatlerinizi kaydetmeye başlayın.",
    "weeklyView": "Haftalık Görünüm",
    "monthlyView": "Aylık Görünüm",
    "timesheetSubmitted": "Zaman çizelgesi gönderildi",
    "timesheetApproved": "Zaman çizelgesi onaylandı",
    "timesheetRejected": "Zaman çizelgesi reddedildi",
    "timesheetSaved": "Zaman çizelgesi kaydedildi",
    "submitConfirm": "Bu zaman çizelgesini göndermek istiyor musunuz? Gönderildikten sonra incelenene kadar düzenlenemez.",
    "workingDay": "İş Günü",
    "weekend": "Hafta Sonu",
    "holiday": "Tatil",
    "selectMonth": "Ay seçin",
    "noTimesheetData": "Zaman çizelgesi verisi yok",
    "noTimesheetDataDesc": "Bu dönem için kayıt bulunamadı."
  },
  "absences": {
    "title": "İzinler",
    "description": "Personel izinlerini ve devamsızlıklarını takip edin",
    "newAbsence": "Yeni İzin",
    "editAbsence": "İzni Düzenle",
    "deleteAbsence": "İzni Sil",
    "deleteAbsenceConfirm": "Bu izin kaydı silinsin mi?",
    "absenceType": "İzin Türü",
    "vacation": "Yıllık İzin",
    "sickLeave": "Hastalık İzni",
    "publicHoliday": "Resmi Tatil",
    "training": "Eğitim",
    "conference": "Konferans",
    "other": "Diğer",
    "startDate": "Başlangıç Tarihi",
    "endDate": "Bitiş Tarihi",
    "days": "Gün",
    "halfDay": "Yarım Gün",
    "reason": "Sebep",
    "noAbsences": "Kayıtlı izin yok",
    "noAbsencesDesc": "Ekip müsaitliğini takip etmek için izinleri kaydedin.",
    "approvers": "Onaylayıcılar",
    "myAbsences": "İzinlerim",
    "teamAbsences": "Ekip İzinleri",
    "timeline": "Zaman Çizelgesi",
    "listView": "Liste Görünümü",
    "absenceCreated": "İzin kaydedildi",
    "absenceUpdated": "İzin güncellendi",
    "absenceDeleted": "İzin silindi",
    "absenceApproved": "İzin onaylandı",
    "absenceRejected": "İzin reddedildi",
    "substitute": "Vekil",
    "selectPerson": "Kişi seçin",
    "daysCount": "{{count}} gün"
  },
  "financials": {
    "title": "Finans",
    "description": "{{year}} için bütçe ve gerçekleşen takibi",
    "budgetOverview": "Bütçe Genel Bakış",
    "enterActuals": "Gerçekleşenleri Gir",
    "expenses": "Giderler",
    "category": "Kategori",
    "amount": "Tutar",
    "personnelBudget": "Personel",
    "travelBudget": "Seyahat",
    "subcontractingBudget": "Alt Yüklenici",
    "otherBudget": "Diğer Doğrudan",
    "indirectCosts": "Dolaylı Maliyetler",
    "totalBudget": "Toplam Bütçe",
    "spent": "Harcanan",
    "remaining": "Kalan",
    "utilization": "Kullanım",
    "syncBudgets": "Projelerden Bütçeleri Senkronize Et",
    "computePersonnel": "Personel Gerçekleşenlerini Hesapla",
    "syncExpenses": "Gider Gerçekleşenlerini Senkronize Et",
    "noFinancialData": "Mali veri yok",
    "noFinancialDataDesc": "Bütçe ve gerçekleşen genel bakışını görmek için projeler ve bütçe girişleri ekleyin.",
    "budgetRowsUpToDate": "Tüm bütçe satırları güncel ve proje verileriyle senkronize.",
    "budgetRowsSynced": "Bütçe satırları: {{details}}.",
    "created": "oluşturuldu",
    "updated": "güncellendi",
    "personnelUpToDate": "Personel gerçekleşenleri zaten tahsis verileriyle eşleşiyor.",
    "personnelSynced": "{{count}} personel gerçekleşen(ler)i tahsis verilerinden güncellendi.",
    "expensesUpToDate": "Personel dışı gerçekleşenler zaten gider kayıtlarıyla eşleşiyor.",
    "expensesSynced": "{{count}} bütçe gerçekleşen(ler)i gider kayıtlarından güncellendi.",
    "under80": "%80'in altında",
    "between80and100": "%80–100",
    "overBudget": "Bütçe aşımı",
    "grandTotal": "TOPLAM",
    "actualsSaved": "Gerçekleşenler kaydedildi"
  },
  "proposals": {
    "title": "Başvurular",
    "description": "Hibe başvurularını takip edin ve onaylananları projelere dönüştürün",
    "newProposal": "Yeni Başvuru",
    "editProposal": "Başvuruyu Düzenle",
    "deleteProposal": "Başvuruyu Sil",
    "deleteProposalConfirm": "\"{{name}}\" başvurusunu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    "proposalCreated": "Başvuru oluşturuldu",
    "proposalUpdated": "Başvuru güncellendi",
    "proposalDeleted": "Başvuru silindi",
    "projectName": "Proje Adı",
    "callIdentifier": "Çağrı Tanımlayıcı",
    "fundingScheme": "Fonlama Programı",
    "submissionDeadline": "Son Başvuru Tarihi",
    "expectedDecision": "Beklenen Karar",
    "approxDecisionDate": "Tahmini Karar Tarihi",
    "ourPms": "Bizim KA'larımız",
    "inPreparation": "Hazırlık Aşamasında",
    "submitted": "Gönderildi",
    "granted": "Onaylandı",
    "rejected": "Reddedildi",
    "convertToProject": "Projeye Dönüştür",
    "convertToProjectConfirm": "Bu, \"{{name}}\" başvurusunun bütçe verileriyle yeni bir proje oluşturacaktır. Proje detaylarını daha sonra düzenleyebilirsiniz. Devam edilsin mi?",
    "projectCreated": "Proje oluşturuldu!",
    "projectCreatedDesc": "Yeni projeye yönlendiriliyor...",
    "converting": "Dönüştürülüyor...",
    "createProject": "Proje Oluştur",
    "pipeline": "Pipeline",
    "noProposals": "Henüz başvuru yok",
    "noProposalsDesc": "Hibe başvurularınızı gönderimden karara kadar takip edin.",
    "addFirstProposal": "İlk başvurunuzu ekleyin",
    "allProposals": "Tüm Başvurular",
    "filteredProposals": "{{status}} Başvurular",
    "budgetBreakdown": "Bütçe Dağılımı",
    "personnelBudget": "Personel Bütçesi",
    "travelBudget": "Seyahat Bütçesi",
    "subcontractingBudget": "Alt Yüklenici Bütçesi",
    "otherBudget": "Diğer Bütçe",
    "totalBudget": "Toplam Bütçe",
    "responsiblePerson": "Sorumlu Kişi",
    "updateProposal": "Başvuruyu Güncelle",
    "createProposal": "Başvuru Oluştur",
    "enterDetails": "Hibe başvurunuzun detaylarını girin.",
    "updateDetails": "Başvuru detaylarını güncelleyin.",
    "searchEuCalls": "AB çağrılarını ara veya tanımlayıcı yazın...",
    "searchEuCallsHint": "Açık AB Fonlama ve İhale çağrılarını aramak için yazmaya başlayın veya herhangi bir tanımlayıcı girin",
    "selectFundingScheme": "Fonlama programı seçin veya yazın...",
    "noMatchingSchemes": "Eşleşen program yok — özel bir tane yazın",
    "goToProject": "Projeye Git"
  },
  "settings": {
    "title": "Ayarlar",
    "description": "Kuruluş ayarları ve yapılandırma",
    "organisation": "Kuruluş",
    "orgName": "Kuruluş Adı",
    "currency": "Para Birimi",
    "workingHours": "Günlük Çalışma Saati",
    "departments": "Departmanlar",
    "users": "Kullanıcılar",
    "members": "Kuruluş Üyeleri",
    "addMember": "Üye Ekle",
    "removeMember": "Üyeyi Kaldır",
    "rolePermissions": "Rol İzinleri",
    "fundingSchemes": "Fonlama Programları",
    "holidays": "Tatiller",
    "periodLocking": "Dönem Kilitleme",
    "language": "Dil",
    "selectLanguage": "Dil seçin",
    "languageDesc": "Tercih ettiğiniz arayüz dilini seçin. Bu ayar profilinize kaydedilir.",
    "general": "Genel",
    "dangerZone": "Tehlikeli Bölge",
    "absenceApprovers": "İzin Onaylayıcıları",
    "absenceTypes": "İzin Türleri",
    "rolePermDesc": "Her rolün ne görebileceğini ve yapabileceğini yapılandırın. Yöneticilerin her zaman tam erişimi vardır. Dış Katılımcılar yalnızca davet edildikleri projelere erişebilir.",
    "moduleVisibility": "Modül Görünürlüğü",
    "whichSections": "Kenar çubuğunda hangi bölümler görünür",
    "sensitiveData": "Hassas Veriler",
    "accessConfidential": "Gizli bilgilere erişim",
    "actionsLabel": "İşlemler",
    "whatRoleCanDo": "Bu rolün oluşturabilecekleri, düzenleyebilecekleri veya yönetebilecekleri",
    "adminNote": "Yönetici rolü her zaman tüm modüllere ve verilere tam erişime sahiptir. Aşağıdaki değişiklikler yalnızca <strong>{{role}}</strong> kullanıcıları için geçerlidir.",
    "resetToDefaults": "Varsayılanlara Sıfırla",
    "saveChanges": "Değişiklikleri Kaydet",
    "resetConfirm": "\"{{role}}\" izinleri sıfırlansın mı?\n\nBu rol için tüm özelleştirmeler kaldırılacaktır.",
    "permissionsSaved": "Rol izinleri güncellendi. Kullanıcılar değişiklikleri bir sonraki girişte görecek.",
    "settingsSaved": "Ayarlar kaydedildi",
    "memberInvited": "Üye davet edildi",
    "memberRemoved": "Üye kaldırıldı",
    "memberRoleUpdated": "Üye rolü güncellendi",
    "schemeAdded": "Fonlama programı eklendi",
    "schemeDeleted": "Fonlama programı silindi",
    "holidayAdded": "Tatil eklendi",
    "holidayDeleted": "Tatil silindi",
    "departmentAdded": "Departman eklendi",
    "departmentDeleted": "Departman silindi",
    "approverAdded": "Onaylayıcı eklendi",
    "approverRemoved": "Onaylayıcı kaldırıldı",
    "periodLocked": "Dönem kilitlendi",
    "periodUnlocked": "Dönem kilidi açıldı"
  },
  "profile": {
    "title": "Ayarlarım",
    "description": "Kişisel profilinizi, şifrenizi ve e-posta bildirim tercihlerinizi yönetin",
    "displayName": "Görünen Ad",
    "changePassword": "Şifreyi Değiştir",
    "currentPassword": "Mevcut Şifre",
    "newPassword": "Yeni Şifre",
    "confirmPassword": "Şifreyi Onayla",
    "emailNotifications": "E-posta Bildirimleri",
    "managePreferences": "Hangi e-posta bildirimlerini alacağınızı yönetin.",
    "profileSection": "Profil",
    "accountInfo": "Hesap bilgileriniz",
    "organisation": "Kuruluş",
    "passwordTooShort": "Şifre en az 6 karakter olmalıdır.",
    "passwordMismatch": "Şifreler uyuşmuyor",
    "passwordUpdated": "Şifre başarıyla güncellendi",
    "profileSaved": "Profil kaydedildi",
    "saveProfile": "Profili Kaydet",
    "updatePassword": "Şifreyi Değiştir",
    "updatingPassword": "Güncelleniyor...",
    "minCharacters": "Min. 6 karakter",
    "reEnterPassword": "Şifreyi tekrar girin",
    "displayNamePlaceholder": "Görünen adınız",
    "dbMigrationNote": "E-posta bildirim tercihleri bir veritabanı geçişi gerektirir. Tercihlerin kaydedilmesini etkinleştirmek için Supabase SQL Düzenleyicinizde <code>supabase/add_user_preferences.sql</code> dosyasını çalıştırın. O zamana kadar tüm bildirimler varsayılan olarak etkindir.",
    "prefsNotAvailable": "Tercihler tablosu henüz mevcut değil. Önce SQL geçişini çalıştırın.",
    "couldNotSave": "Kaydedilemedi — tercihler tablosu henüz ayarlanmamış olabilir.",
    "couldNotSavePref": "Tercih kaydedilemedi — tablo henüz ayarlanmamış olabilir.",
    "languageChanged": "Arayüz dili {{language}} olarak değiştirildi"
  },
  "reports": {
    "title": "Raporlar",
    "generateReport": "Rapor Oluştur",
    "projectSummary": "Proje Özeti",
    "financialReport": "Mali Rapor",
    "timesheetReport": "Zaman Çizelgesi Raporu",
    "staffAllocations": "Personel Tahsisleri",
    "absenceSummary": "İzin Özeti",
    "reportGenerated": "Rapor oluşturuldu",
    "generating": "Oluşturuluyor..."
  },
  "guests": {
    "title": "Misafir Erişimi",
    "inviteGuest": "Misafir Davet Et",
    "guestEmail": "Misafir E-postası",
    "projectAccess": "Proje Erişimi",
    "accessLevel": "Erişim Düzeyi",
    "revokeAccess": "Erişimi İptal Et"
  },
  "audit": {
    "title": "Denetim Kaydı",
    "action": "İşlem",
    "entity": "Varlık",
    "user": "Kullanıcı",
    "timestamp": "Zaman Damgası",
    "details": "Detaylar"
  },
  "import": {
    "title": "İçe Aktar",
    "importData": "Veri İçe Aktar",
    "selectFile": "Dosya Seç",
    "dragAndDrop": "Bir dosyayı buraya sürükleyip bırakın",
    "supportedFormats": "Desteklenen formatlar: CSV, XLSX",
    "processing": "İşleniyor...",
    "mapping": "Sütunları Eşle",
    "preview": "Ön İzleme",
    "importComplete": "İçe aktarma tamamlandı",
    "importFailed": "İçe aktarma başarısız",
    "rowsImported": "{{count}} satır içe aktarıldı",
    "downloadTemplate": "Şablon İndir",
    "step1Upload": "Yükle",
    "step2Processing": "İşleme",
    "step3Map": "Eşle",
    "step4Preview": "Ön İzleme"
  },
  "documents": {
    "title": "Belgeler",
    "uploadDocument": "Belge Yükle",
    "deleteDocument": "Belgeyi Sil",
    "deleteDocumentConfirm": "\"{{name}}\" silinsin mi?",
    "documentUploaded": "Belge yüklendi",
    "documentDeleted": "Belge silindi",
    "noDocuments": "Belge yok",
    "noDocumentsDesc": "Her şeyi düzenli tutmak için proje belgelerini yükleyin.",
    "fileName": "Dosya Adı",
    "fileSize": "Boyut",
    "uploadedBy": "Yükleyen",
    "uploadedAt": "Yüklenme Tarihi"
  },
  "collaboration": {
    "title": "İş Birliği Projeleri",
    "description": "Çok ortaklı iş birliği projelerini yönetin",
    "newProject": "Yeni İş Birliği Projesi",
    "editProject": "Projeyi Düzenle",
    "deleteProject": "Projeyi Sil",
    "projectCreated": "İş birliği projesi oluşturuldu",
    "projectUpdated": "İş birliği projesi güncellendi",
    "projectDeleted": "İş birliği projesi silindi",
    "partners": "Ortaklar",
    "addPartner": "Ortak Ekle",
    "editPartner": "Ortağı Düzenle",
    "deletePartner": "Ortağı Sil",
    "partnerAdded": "Ortak eklendi",
    "partnerUpdated": "Ortak güncellendi",
    "partnerDeleted": "Ortak silindi",
    "contacts": "Kişiler",
    "addContact": "Kişi Ekle",
    "editContact": "Kişiyi Düzenle",
    "deleteContact": "Kişiyi Sil",
    "contactAdded": "Kişi eklendi",
    "contactUpdated": "Kişi güncellendi",
    "contactDeleted": "Kişi silindi",
    "allocations": "Tahsisler",
    "tasks": "Görevler",
    "noProjects": "Henüz iş birliği projesi yok",
    "noProjectsDesc": "Çok ortaklı çalışmayı yönetmek için bir iş birliği projesi oluşturun.",
    "totalBudget": "Toplam Bütçe",
    "ourShare": "Bizim Payımız",
    "setup": "Kurulum"
  },
  "onboarding": {
    "title": "GrantLume'a Hoş Geldiniz",
    "createOrg": "Kuruluşunuzu oluşturun",
    "orgNameLabel": "Kuruluş Adı",
    "currencyLabel": "Varsayılan Para Birimi",
    "letsGo": "Haydi başlayalım!",
    "settingUp": "Kuruluyor..."
  },
  "notifications": {
    "title": "Bildirimler",
    "markAllRead": "Tümünü okundu işaretle",
    "noNotifications": "Bildirim yok",
    "clearRead": "Okunanları temizle"
  },
  "topbar": {
    "mySettings": "Ayarlarım",
    "signOut": "Çıkış yap",
    "darkMode": "Karanlık modu aç/kapat",
    "year": "Yıl",
    "trialDaysRemaining": "Deneme: {{days}} gün kaldı",
    "member": "Üye"
  },
  "landing": {
    "hero": "Modern Hibe Yönetim Platformu",
    "heroSub": "AB ve kamu fonlu proje yönetiminizi tahsisler, zaman çizelgeleri, finans ve raporlama için güçlü araçlarla optimize edin.",
    "getStarted": "Ücretsiz başla",
    "viewDemo": "Demoyu gör",
    "trustedBy": "Avrupa genelinde araştırma kuruluşları tarafından güvenilir"
  },
  "empty": {
    "noData": "Veri mevcut değil",
    "getStarted": "İlk öğenizi oluşturarak başlayın."
  },
  "validation": {
    "required": "Bu alan zorunludur",
    "invalidEmail": "Lütfen geçerli bir e-posta adresi girin",
    "minLength": "En az {{min}} karakter olmalıdır",
    "maxLength": "En fazla {{max}} karakter olmalıdır",
    "passwordMinLength": "Şifre en az 8 karakter olmalıdır",
    "projectNameRequired": "Proje adı zorunludur"
  },
  "time": {
    "jan": "Oca", "feb": "Şub", "mar": "Mar", "apr": "Nis",
    "may": "May", "jun": "Haz", "jul": "Tem", "aug": "Ağu",
    "sep": "Eyl", "oct": "Eki", "nov": "Kas", "dec": "Ara",
    "monday": "Pazartesi", "tuesday": "Salı", "wednesday": "Çarşamba",
    "thursday": "Perşembe", "friday": "Cuma", "saturday": "Cumartesi", "sunday": "Pazar",
    "today": "Bugün", "yesterday": "Dün", "tomorrow": "Yarın",
    "thisWeek": "Bu hafta", "thisMonth": "Bu ay", "thisYear": "Bu yıl"
  }
};

fs.writeFileSync(path.join(localesDir, 'tr.json'), JSON.stringify(tr, null, 2) + '\n');
console.log('✓ tr.json written');

const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));
let missing = 0;
for (const section of Object.keys(en)) {
  if (!tr[section]) { console.log(`  ✗ Missing section: ${section}`); missing++; continue; }
  for (const key of Object.keys(en[section])) {
    if (typeof en[section][key] === 'object') {
      if (!tr[section][key]) { console.log(`  ✗ Missing nested: ${section}.${key}`); missing++; continue; }
      for (const subkey of Object.keys(en[section][key])) {
        if (tr[section][key][subkey] === undefined) { console.log(`  ✗ Missing: ${section}.${key}.${subkey}`); missing++; }
      }
    } else {
      if (tr[section][key] === undefined) { console.log(`  ✗ Missing: ${section}.${key}`); missing++; }
    }
  }
}
if (missing === 0) console.log('✓ All keys present in tr.json');
else console.log(`✗ ${missing} missing key(s)`);
