const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '..', 'src', 'locales');

const es = {
  "nav": {
    "core": "Principal",
    "operations": "Operaciones",
    "administration": "Administración",
    "dashboard": "Panel",
    "projects": "Nuestros Proyectos",
    "proposals": "Propuestas",
    "staff": "Personal",
    "allocations": "Asignaciones",
    "timesheets": "Hojas de tiempo",
    "absences": "Ausencias",
    "financials": "Finanzas",
    "timeline": "Cronología",
    "reports": "Informes",
    "import": "Importar",
    "auditLog": "Registro de auditoría",
    "collaboration": "Colaboración",
    "settings": "Configuración",
    "projectOverview": "Resumen del proyecto",
    "help": "Ayuda y FAQ"
  },
  "common": {
    "save": "Guardar",
    "cancel": "Cancelar",
    "delete": "Eliminar",
    "edit": "Editar",
    "create": "Crear",
    "add": "Añadir",
    "remove": "Quitar",
    "close": "Cerrar",
    "confirm": "Confirmar",
    "back": "Volver",
    "next": "Siguiente",
    "search": "Buscar",
    "filter": "Filtrar",
    "export": "Exportar",
    "loading": "Cargando...",
    "saving": "Guardando...",
    "deleting": "Eliminando...",
    "noResults": "No se encontraron resultados",
    "error": "Error",
    "success": "Éxito",
    "warning": "Advertencia",
    "actions": "Acciones",
    "status": "Estado",
    "name": "Nombre",
    "email": "Correo electrónico",
    "role": "Rol",
    "date": "Fecha",
    "type": "Tipo",
    "description": "Descripción",
    "notes": "Notas",
    "total": "Total",
    "active": "Activo",
    "inactive": "Inactivo",
    "all": "Todos",
    "yes": "Sí",
    "no": "No",
    "or": "o",
    "and": "y",
    "of": "de",
    "to": "a",
    "from": "de",
    "submit": "Enviar",
    "approve": "Aprobar",
    "reject": "Rechazar",
    "pending": "Pendiente",
    "approved": "Aprobado",
    "rejected": "Rechazado",
    "download": "Descargar",
    "upload": "Subir",
    "refresh": "Actualizar",
    "reset": "Restablecer",
    "selectAll": "Seleccionar todo",
    "deselectAll": "Deseleccionar todo",
    "showing": "Mostrando",
    "items": "elementos",
    "page": "Página",
    "previous": "Anterior",
    "rows": "filas",
    "columns": "Columnas",
    "viewAll": "Ver todo",
    "learnMore": "Más información",
    "required": "Obligatorio",
    "optional": "Opcional",
    "synced": "Sincronizado",
    "upToDate": "Actualizado",
    "syncing": "Sincronizando...",
    "computing": "Calculando...",
    "adding": "Añadiendo...",
    "updating": "Actualizando...",
    "project": "Proyecto",
    "projects": "proyectos",
    "budget": "Presupuesto",
    "actual": "Real",
    "remaining": "Restante",
    "over": "Exceso",
    "period": "Período",
    "title": "Título",
    "acronym": "Acrónimo",
    "scheme": "Programa",
    "lead": "Responsable",
    "programme": "Programa",
    "partners": "Socios",
    "searchPlaceholder": "Buscar por acrónimo o título...",
    "noProjectsFound": "No se encontraron proyectos",
    "tryAdjusting": "Intente ajustar su búsqueda.",
    "createFirstProject": "Cree su primer proyecto para comenzar.",
    "showingCount": "Mostrando {{count}} proyecto(s)",
    "deleteProject": "Eliminar proyecto",
    "deleteProjectConfirm": "¿Está seguro de que desea eliminar \"{{name}}\"? Se eliminarán también todos los paquetes de trabajo, asignaciones y hojas de tiempo asociados.",
    "deleted": "Eliminado",
    "hasBeenRemoved": "{{name}} ha sido eliminado.",
    "failedToDelete": "Error al eliminar",
    "failedToSave": "Error al guardar",
    "suspended": "Suspendido",
    "upcoming": "Próximo",
    "none": "Ninguno",
    "member": "Miembro",
    "person": "Persona",
    "amount": "Importe",
    "vendor": "Proveedor",
    "reference": "Referencia",
    "category": "Categoría",
    "update": "Actualizar",
    "record": "Registrar",
    "invited": "Invitado",
    "account": "Cuenta",
    "overBudget": "Sobre presupuesto",
    "noneSelected": "— Ninguno —",
    "ref": "Ref: {{ref}}",
    "countItems": "{{count}} {{item}}",
    "allCategories": "Todas las categorías",
    "exportPdf": "Exportar PDF"
  },
  "auth": {
    "login": "Iniciar sesión",
    "logout": "Cerrar sesión",
    "signUp": "Registrarse",
    "signIn": "Iniciar sesión",
    "forgotPassword": "¿Olvidó su contraseña?",
    "resetPassword": "Restablecer contraseña",
    "setNewPassword": "Establecer nueva contraseña",
    "email": "Correo electrónico",
    "password": "Contraseña",
    "confirmPassword": "Confirmar contraseña",
    "firstName": "Nombre",
    "lastName": "Apellido",
    "rememberMe": "Mantener sesión iniciada",
    "createAccount": "Crear su cuenta",
    "alreadyHaveAccount": "¿Ya tiene una cuenta?",
    "dontHaveAccount": "¿No tiene cuenta?",
    "termsAgree": "Al hacer clic, confirma que ha leído y acepta los",
    "termsOfUse": "Términos de uso",
    "privacyPolicy": "Política de privacidad",
    "startTrial": "Prueba gratuita de 14 días",
    "noPaymentRequired": "No se requiere información de pago",
    "startUsingImmediately": "Comience a usar GrantLume inmediatamente",
    "noInstallation": "Sin instalación",
    "cloudBased": "En la nube — funciona en su navegador",
    "trialAutoEnds": "El período de prueba de 14 días termina automáticamente",
    "noObligations": "Sin obligaciones, cancele en cualquier momento",
    "registerFree": "Registrarse gratis",
    "startFreeTrial": "Comience su prueba gratuita de 14 días — sin tarjeta de crédito",
    "creatingAccount": "Creando cuenta...",
    "checkYourEmail": "Revise su correo",
    "confirmationSent": "Hemos enviado un enlace de confirmación a",
    "clickToActivate": "Haga clic en el enlace para activar su cuenta y comenzar su prueba gratuita de 14 días.",
    "didntReceive": "¿No recibió el correo? Revise su carpeta de spam o espere unos minutos.",
    "resendConfirmation": "Reenviar correo de confirmación",
    "goToLogin": "Ir al inicio de sesión",
    "passwordStrength": "Fortaleza de la contraseña",
    "weak": "Débil",
    "fair": "Regular",
    "good": "Buena",
    "strong": "Fuerte",
    "passwordsDoNotMatch": "Las contraseñas no coinciden",
    "accountRecovery": "Recuperación de cuenta",
    "wellHelpYouBack": "Le ayudaremos a recuperar el acceso a su cuenta",
    "sendResetLink": "Enviar enlace",
    "sendingResetLink": "Enviando...",
    "resetLinkSent": "Revise su correo",
    "resetLinkSentDesc": "Si existe una cuenta con ese correo, recibirá un enlace de restablecimiento.",
    "backToLogin": "Volver al inicio de sesión",
    "chooseStrongPassword": "Elija una contraseña fuerte y única",
    "newPassword": "Nueva contraseña",
    "updatePassword": "Actualizar contraseña",
    "updatingPassword": "Actualizando...",
    "passwordUpdated": "Contraseña actualizada",
    "canNowSignIn": "Ahora puede iniciar sesión con su nueva contraseña",
    "securityCheck": "Verificación de seguridad",
    "solveToProve": "Resuelva esto para demostrar que es humano",
    "tooManyAttempts": "Demasiados intentos fallidos. Inténtelo más tarde."
  },
  "callback": {
    "verifying": "Verificando...",
    "pleaseWait": "Por favor espere mientras confirmamos su cuenta",
    "emailConfirmed": "¡Correo confirmado!",
    "accountVerified": "Su cuenta ha sido verificada correctamente. Está listo para configurar su organización y comenzar a gestionar sus subvenciones.",
    "whatsNext": "¿Qué sigue?",
    "step1": "Cree su organización",
    "step2": "Añada su primer proyecto",
    "step3": "Invite a los miembros de su equipo",
    "continueToSetup": "Continuar con la configuración",
    "youreAllSet": "¡Todo listo!",
    "verifiedRedirecting": "¡Verificado! Redirigiendo...",
    "verificationFailed": "Error en la verificación",
    "linkExpired": "No se pudo verificar su correo. El enlace puede haber expirado o ya fue utilizado. Por favor intente iniciar sesión."
  },
  "dashboard": {
    "title": "Panel",
    "welcome": "Bienvenido de nuevo",
    "overview": "Resumen",
    "activeProjects": "Proyectos activos",
    "totalStaff": "Personal total",
    "pendingTimesheets": "Hojas de tiempo pendientes",
    "upcomingDeadlines": "Plazos próximos",
    "recentActivity": "Actividad reciente",
    "quickActions": "Acciones rápidas",
    "budgetOverview": "Resumen de presupuesto",
    "projectStatus": "Estado del proyecto",
    "portfolioOverview": "Resumen del portafolio — {{year}}",
    "kpiProjects": "Proyectos",
    "kpiStaff": "Personal",
    "kpiTotalBudget": "Presupuesto total",
    "kpiPersonMonths": "Persona-mes",
    "kpiProposals": "Propuestas",
    "kpiCollaborations": "Colaboraciones",
    "activeCount": "{{count}} activo(s)",
    "submittedCount": "{{count}} enviado(s)",
    "acrossAllProjects": "en todos los proyectos",
    "actualIn": "real en {{year}}",
    "plannedIn": "planificado en {{year}}",
    "projectsEndingSoon": "{{count}} proyecto(s) terminando pronto: {{names}}",
    "staffOverAllocated": "{{count}} miembro(s) del personal sobreasignado(s) este año",
    "monthlyAllocations": "Asignaciones mensuales (PM)",
    "projectStatusDistribution": "Distribución de estados de proyecto",
    "noProjectsYet": "Aún no hay proyectos",
    "projectsOverview": "Resumen de proyectos",
    "pmsYear": "PM ({{year}})"
  },
  "projects": {
    "title": "Nuestros Proyectos",
    "description": "La participación de su organización en cada proyecto",
    "newProject": "Nuevo proyecto",
    "editProject": "Editar proyecto",
    "importWithAI": "Importar con IA",
    "projectDetails": "Detalles del proyecto",
    "acronym": "Acrónimo",
    "fullTitle": "Título completo",
    "startDate": "Fecha de inicio",
    "endDate": "Fecha de fin",
    "fundingScheme": "Programa de financiación",
    "budget": "Presupuesto",
    "responsiblePerson": "Persona responsable",
    "workPackages": "Paquetes de trabajo",
    "deliverables": "Entregables",
    "milestones": "Hitos",
    "personnel": "Personal",
    "documents": "Documentos",
    "expenses": "Gastos",
    "noProjects": "Aún no hay proyectos",
    "noProjectsDesc": "Cree su primer proyecto para comenzar.",
    "status": "Estado",
    "active": "Activo",
    "completed": "Completado",
    "preparation": "En preparación",
    "pmRate": "Tasa PM",
    "totalBudget": "Presupuesto total",
    "spentBudget": "Gastado",
    "remainingBudget": "Restante",
    "collaboration": "Colaboración",
    "collaborationProjects": "Proyectos de colaboración",
    "notFound": "Proyecto no encontrado",
    "backToProjects": "Volver a proyectos",
    "overview": "Resumen",
    "reporting": "Informes",
    "grantNumber": "Número de subvención",
    "ledByOurOrg": "Liderado por nuestra organización",
    "budgetBreakdown": "Desglose de presupuesto",
    "travel": "Viajes",
    "subcontracting": "Subcontratación",
    "other": "Otros",
    "otherDirectCosts": "Otros costes directos",
    "indirectCosts": "Costes indirectos",
    "overheadRate": "Tasa de gastos generales",
    "ourPmRate": "Nuestra tasa PM",
    "personMonthsPerYear": "Persona-mes por año",
    "totalAcrossYears": "Total en todos los años",
    "assignedToWPs": "Asignado a PTs",
    "ofBudget": "del presupuesto",
    "allocated": "Asignado",
    "peopleAllocated": "Personas asignadas al proyecto",
    "remaining": "Restante",
    "budgetMinusAllocated": "Presupuesto menos asignado",
    "projectBudget": "Presupuesto del proyecto",
    "pmBudgetDistribution": "Distribución del presupuesto PM",
    "unassigned": "No asignado",
    "addWorkPackage": "Añadir paquete de trabajo",
    "wpNumber": "PT #",
    "wpName": "Nombre",
    "wpDescription": "Descripción",
    "startMonth": "Mes de inicio",
    "endMonth": "Mes de fin",
    "addWP": "Añadir PT",
    "wpAdded": "Paquete de trabajo añadido",
    "wpDeleted": "Paquete de trabajo eliminado",
    "wpUpdated": "Paquete de trabajo actualizado.",
    "deleteWP": "Eliminar paquete de trabajo",
    "deleteWPConfirm": "¿Está seguro de que desea eliminar \"{{name}}\"?",
    "budgetPM": "Presupuesto PM",
    "savePmBudgets": "Guardar presupuestos PM",
    "pmBudgetsUpdated": "Presupuestos PM actualizados.",
    "wpPmBudgetsUpdated": "Presupuestos PM de PT actualizados.",
    "projectDuration": "Duración del proyecto: {{months}} meses ({{start}} – {{end}})"
  },
  "expenses": {
    "title": "Gastos",
    "recordExpense": "Registrar gasto",
    "editExpense": "Editar gasto",
    "deleteExpense": "Eliminar gasto",
    "deleteExpenseConfirm": "¿Eliminar \"{{name}}\" ({{amount}})?",
    "expenseRecorded": "Gasto registrado",
    "expenseUpdated": "Gasto actualizado",
    "expenseDeleted": "Gasto eliminado",
    "invalidAmount": "Importe inválido",
    "noExpenses": "Sin gastos registrados",
    "noExpensesDesc": "Registre gastos del proyecto para seguir el consumo del presupuesto en viajes, subcontratación y otras categorías.",
    "spent": "Gastado",
    "budgetForCategory": "Presupuesto para {{category}}:",
    "afterThisExpense": "Después de este gasto:",
    "remainingAfter": "{{amount}} restante",
    "overBudgetAfter": "{{amount}} sobre presupuesto",
    "budgetAlertMessage": "El presupuesto de {{category}} está consumido al {{spentPct}}% pero solo ha transcurrido el {{timelinePct}}% de la duración del proyecto.",
    "descriptionPlaceholder": "Ej. Vuelo a Bruselas para reunión del consorcio",
    "vendorPlaceholder": "Ej. Iberia, Hotel Bruselas",
    "referencePlaceholder": "Ej. FACT-2026-001",
    "additionalDetails": "Detalles adicionales...",
    "vendorPayee": "Proveedor / Beneficiario",
    "referenceInvoice": "Referencia / N° de factura",
    "expenseCount": "{{count}} gasto",
    "expenseCountPlural": "{{count}} gastos"
  },
  "deliverables": {
    "title": "Entregables",
    "addDeliverable": "Añadir entregable",
    "editDeliverable": "Editar entregable",
    "deleteDeliverable": "Eliminar entregable",
    "deleteDeliverableConfirm": "¿Eliminar entregable \"{{name}}\"?",
    "deliverableAdded": "Entregable añadido",
    "deliverableUpdated": "Entregable actualizado",
    "deliverableDeleted": "Entregable eliminado",
    "noDeliverables": "Sin entregables",
    "noDeliverablesDesc": "Añada entregables al proyecto para seguir los resultados y plazos.",
    "number": "Número",
    "dueMonth": "Mes de vencimiento",
    "workPackage": "Paquete de trabajo",
    "addMilestone": "Añadir hito",
    "editMilestone": "Editar hito",
    "deleteMilestone": "Eliminar hito",
    "deleteMilestoneConfirm": "¿Eliminar hito \"{{name}}\"?",
    "milestoneAdded": "Hito añadido",
    "milestoneUpdated": "Hito actualizado",
    "milestoneDeleted": "Hito eliminado",
    "noMilestones": "Sin hitos",
    "noMilestonesDesc": "Añada hitos al proyecto para seguir los logros clave.",
    "verificationMeans": "Medios de verificación"
  },
  "reporting": {
    "title": "Períodos de informe",
    "addPeriod": "Añadir período",
    "editPeriod": "Editar período",
    "deletePeriod": "Eliminar período",
    "deletePeriodConfirm": "¿Eliminar período de informe #{{number}}?",
    "periodAdded": "Período de informe añadido",
    "periodUpdated": "Período de informe actualizado",
    "periodDeleted": "Período de informe eliminado",
    "noPeriods": "Sin períodos de informe",
    "noPeriodsDesc": "Añada períodos de informe para seguir los plazos de revisión.",
    "periodNumber": "Período #",
    "technicalReportDue": "Informe técnico a entregar",
    "financialReportDue": "Informe financiero a entregar"
  },
  "budgetChart": {
    "title": "Consumo de presupuesto",
    "budgeted": "Presupuestado",
    "actual": "Real",
    "percentUsed": "{{percent}}% utilizado",
    "noData": "No hay datos de presupuesto disponibles para este proyecto.",
    "timeElapsed": "{{percent}}% del tiempo del proyecto transcurrido",
    "overSpending": "El gasto va por delante del calendario",
    "underSpending": "El gasto va según lo previsto",
    "categories": {
      "personnel": "Personal",
      "travel": "Viajes",
      "subcontracting": "Subcontratación",
      "other": "Otros",
      "indirect": "Indirecto"
    }
  },
  "staff": {
    "title": "Personal",
    "addPerson": "Añadir nueva persona",
    "editPerson": "Editar persona",
    "fullName": "Nombre completo",
    "department": "Departamento",
    "role": "Rol",
    "employmentType": "Tipo de empleo",
    "fte": "ETC",
    "startDate": "Fecha de inicio",
    "endDate": "Fecha de fin",
    "salary": "Salario anual",
    "vacationDays": "Días de vacaciones",
    "country": "País",
    "isActive": "Activo",
    "noStaff": "Aún no hay personal",
    "noStaffDesc": "Añada su primer miembro del equipo para comenzar.",
    "inviteToSystem": "Invitar a GrantLume",
    "accountStatus": "Estado de la cuenta",
    "sendInvitation": "Enviar invitación",
    "resendInvitation": "Reenviar invitación",
    "personCreated": "Persona creada",
    "personUpdated": "Persona actualizada",
    "personDeleted": "Persona eliminada",
    "deletePerson": "Eliminar persona",
    "deletePersonConfirm": "¿Está seguro de que desea eliminar \"{{name}}\"?",
    "searchPlaceholder": "Buscar personal...",
    "leaveBalance": "Saldo de permisos",
    "leaveUsed": "{{used}} / {{total}} días utilizados",
    "overheadRate": "Tasa de gastos generales",
    "phone": "Teléfono",
    "avatar": "Avatar",
    "uploadAvatar": "Subir avatar",
    "removeAvatar": "Eliminar avatar",
    "personalInfo": "Información personal",
    "employmentDetails": "Detalles de empleo",
    "financialInfo": "Información financiera",
    "invitationSent": "Invitación enviada",
    "invitationResent": "Invitación reenviada",
    "invitingUser": "Invitando...",
    "systemRole": "Rol del sistema",
    "projectsInvolved": "Proyectos involucrados"
  },
  "allocations": {
    "title": "Asignaciones",
    "description": "Gestionar asignaciones de persona-mes entre proyectos",
    "personMonth": "Persona-mes",
    "personMonths": "Persona-meses",
    "pm": "PM",
    "capacity": "Capacidad",
    "overAllocated": "Sobreasignado",
    "unsavedChanges": "Cambios sin guardar",
    "pmBudgets": "Presupuestos PM",
    "bulkFill": "Rellenado masivo",
    "addRow": "Añadir fila",
    "undo": "Deshacer",
    "redo": "Rehacer",
    "allocationGrid": "Cuadrícula de asignaciones",
    "personnelOverview": "Resumen de personal",
    "projectOverview": "Resumen de proyecto",
    "periodLocks": "Bloqueos de período",
    "saved": "Asignaciones guardadas",
    "selectPerson": "Seleccionar persona",
    "selectProject": "Seleccionar proyecto",
    "selectWorkPackage": "Seleccionar paquete de trabajo"
  },
  "timesheets": {
    "title": "Hojas de tiempo",
    "myTimesheet": "Mi hoja de tiempo",
    "allTimesheets": "Todas las hojas de tiempo",
    "submitTimesheet": "Enviar hoja de tiempo",
    "approveTimesheets": "Aprobar hojas de tiempo",
    "hours": "Horas",
    "totalHours": "Total de horas",
    "period": "Período",
    "submitted": "Enviado",
    "draft": "Borrador",
    "noEntries": "Aún no hay registros",
    "noEntriesDesc": "Comience a registrar sus horas para este período.",
    "weeklyView": "Vista semanal",
    "monthlyView": "Vista mensual",
    "timesheetSubmitted": "Hoja de tiempo enviada",
    "timesheetApproved": "Hoja de tiempo aprobada",
    "timesheetRejected": "Hoja de tiempo rechazada",
    "timesheetSaved": "Hoja de tiempo guardada",
    "submitConfirm": "¿Enviar esta hoja de tiempo? Una vez enviada, no podrá editarse hasta su revisión.",
    "workingDay": "Día laborable",
    "weekend": "Fin de semana",
    "holiday": "Festivo",
    "selectMonth": "Seleccionar mes",
    "noTimesheetData": "Sin datos de hojas de tiempo",
    "noTimesheetDataDesc": "No se encontraron registros para este período."
  },
  "absences": {
    "title": "Ausencias",
    "description": "Seguir ausencias y permisos del personal",
    "newAbsence": "Nueva ausencia",
    "editAbsence": "Editar ausencia",
    "deleteAbsence": "Eliminar ausencia",
    "deleteAbsenceConfirm": "¿Eliminar este registro de ausencia?",
    "absenceType": "Tipo de ausencia",
    "vacation": "Vacaciones",
    "sickLeave": "Baja por enfermedad",
    "publicHoliday": "Festivo",
    "training": "Formación",
    "conference": "Conferencia",
    "other": "Otro",
    "startDate": "Fecha de inicio",
    "endDate": "Fecha de fin",
    "days": "Días",
    "halfDay": "Medio día",
    "reason": "Motivo",
    "noAbsences": "Sin ausencias registradas",
    "noAbsencesDesc": "Registre ausencias para seguir la disponibilidad del equipo.",
    "approvers": "Aprobadores",
    "myAbsences": "Mis ausencias",
    "teamAbsences": "Ausencias del equipo",
    "timeline": "Cronología",
    "listView": "Vista de lista",
    "absenceCreated": "Ausencia registrada",
    "absenceUpdated": "Ausencia actualizada",
    "absenceDeleted": "Ausencia eliminada",
    "absenceApproved": "Ausencia aprobada",
    "absenceRejected": "Ausencia rechazada",
    "substitute": "Sustituto",
    "selectPerson": "Seleccionar persona",
    "daysCount": "{{count}} día(s)"
  },
  "financials": {
    "title": "Finanzas",
    "description": "Seguimiento presupuesto vs. real para {{year}}",
    "budgetOverview": "Resumen de presupuesto",
    "enterActuals": "Introducir reales",
    "expenses": "Gastos",
    "category": "Categoría",
    "amount": "Importe",
    "personnelBudget": "Personal",
    "travelBudget": "Viajes",
    "subcontractingBudget": "Subcontratación",
    "otherBudget": "Otros directos",
    "indirectCosts": "Costes indirectos",
    "totalBudget": "Presupuesto total",
    "spent": "Gastado",
    "remaining": "Restante",
    "utilization": "Utilización",
    "syncBudgets": "Sincronizar presupuestos desde proyectos",
    "computePersonnel": "Calcular reales de personal",
    "syncExpenses": "Sincronizar reales de gastos",
    "noFinancialData": "Sin datos financieros",
    "noFinancialDataDesc": "Añada proyectos y entradas de presupuesto para ver el resumen presupuesto vs. real.",
    "budgetRowsUpToDate": "Todas las filas de presupuesto están actualizadas y sincronizadas con los datos del proyecto.",
    "budgetRowsSynced": "Filas de presupuesto: {{details}}.",
    "created": "creado",
    "updated": "actualizado",
    "personnelUpToDate": "Los reales de personal ya coinciden con los datos de asignación.",
    "personnelSynced": "{{count}} real(es) de personal actualizado(s) desde datos de asignación.",
    "expensesUpToDate": "Los reales no de personal ya coinciden con los registros de gastos.",
    "expensesSynced": "{{count}} real(es) de presupuesto actualizado(s) desde registros de gastos.",
    "under80": "Menos del 80%",
    "between80and100": "80–100%",
    "overBudget": "Sobre presupuesto",
    "grandTotal": "TOTAL",
    "actualsSaved": "Reales guardados"
  },
  "proposals": {
    "title": "Propuestas",
    "description": "Seguir solicitudes de subvención y convertir las concedidas en proyectos",
    "newProposal": "Nueva propuesta",
    "editProposal": "Editar propuesta",
    "deleteProposal": "Eliminar propuesta",
    "deleteProposalConfirm": "¿Está seguro de que desea eliminar \"{{name}}\"? Esta acción no se puede deshacer.",
    "proposalCreated": "Propuesta creada",
    "proposalUpdated": "Propuesta actualizada",
    "proposalDeleted": "Propuesta eliminada",
    "projectName": "Nombre del proyecto",
    "callIdentifier": "Identificador de convocatoria",
    "fundingScheme": "Programa de financiación",
    "submissionDeadline": "Fecha límite de envío",
    "expectedDecision": "Decisión esperada",
    "approxDecisionDate": "Fecha de decisión aproximada",
    "ourPms": "Nuestros PMs",
    "inPreparation": "En preparación",
    "submitted": "Enviado",
    "granted": "Concedido",
    "rejected": "Rechazado",
    "convertToProject": "Convertir en proyecto",
    "convertToProjectConfirm": "Esto creará un nuevo proyecto a partir de \"{{name}}\" con los datos presupuestarios de la propuesta. Podrá editar los detalles del proyecto después. ¿Continuar?",
    "projectCreated": "¡Proyecto creado!",
    "projectCreatedDesc": "Redirigiendo al nuevo proyecto...",
    "converting": "Convirtiendo...",
    "createProject": "Crear proyecto",
    "pipeline": "Pipeline",
    "noProposals": "Aún no hay propuestas",
    "noProposalsDesc": "Siga sus propuestas de subvención desde el envío hasta la decisión.",
    "addFirstProposal": "Añada su primera propuesta",
    "allProposals": "Todas las propuestas",
    "filteredProposals": "Propuestas {{status}}",
    "budgetBreakdown": "Desglose de presupuesto",
    "personnelBudget": "Presupuesto de personal",
    "travelBudget": "Presupuesto de viajes",
    "subcontractingBudget": "Presupuesto de subcontratación",
    "otherBudget": "Otro presupuesto",
    "totalBudget": "Presupuesto total",
    "responsiblePerson": "Persona responsable",
    "updateProposal": "Actualizar propuesta",
    "createProposal": "Crear propuesta",
    "enterDetails": "Introduzca los detalles de su solicitud de subvención.",
    "updateDetails": "Actualice los detalles de la propuesta.",
    "searchEuCalls": "Buscar convocatorias UE o escribir identificador...",
    "searchEuCallsHint": "Comience a escribir para buscar convocatorias abiertas de EU Funding & Tenders, o introduzca cualquier identificador",
    "selectFundingScheme": "Seleccionar o escribir un programa de financiación...",
    "noMatchingSchemes": "Sin programas coincidentes — escriba uno personalizado",
    "goToProject": "Ir al proyecto"
  },
  "settings": {
    "title": "Configuración",
    "description": "Configuración y ajustes de la organización",
    "organisation": "Organización",
    "orgName": "Nombre de la organización",
    "currency": "Moneda",
    "workingHours": "Horas de trabajo por día",
    "departments": "Departamentos",
    "users": "Usuarios",
    "members": "Miembros de la organización",
    "addMember": "Añadir miembro",
    "removeMember": "Quitar miembro",
    "rolePermissions": "Permisos de roles",
    "fundingSchemes": "Programas de financiación",
    "holidays": "Festivos",
    "periodLocking": "Bloqueo de períodos",
    "language": "Idioma",
    "selectLanguage": "Seleccionar idioma",
    "languageDesc": "Elija su idioma de interfaz preferido. Este ajuste se guarda en su perfil.",
    "general": "General",
    "dangerZone": "Zona de peligro",
    "absenceApprovers": "Aprobadores de ausencias",
    "absenceTypes": "Tipos de ausencias",
    "rolePermDesc": "Configure lo que cada rol puede ver y hacer. Los administradores siempre tienen acceso completo. Los participantes externos solo pueden acceder a los proyectos a los que están invitados.",
    "moduleVisibility": "Visibilidad de módulos",
    "whichSections": "Qué secciones aparecen en la barra lateral",
    "sensitiveData": "Datos sensibles",
    "accessConfidential": "Acceso a información confidencial",
    "actionsLabel": "Acciones",
    "whatRoleCanDo": "Lo que este rol puede crear, editar o gestionar",
    "adminNote": "El rol de administrador siempre tiene acceso completo a todos los módulos y datos. Los cambios a continuación se aplican solo a los usuarios <strong>{{role}}</strong>.",
    "resetToDefaults": "Restablecer valores predeterminados",
    "saveChanges": "Guardar cambios",
    "resetConfirm": "¿Restablecer permisos de \"{{role}}\"?\n\nEsto descartará todas las personalizaciones para este rol.",
    "permissionsSaved": "Permisos de rol actualizados. Los usuarios verán los cambios en el próximo inicio de sesión.",
    "settingsSaved": "Configuración guardada",
    "memberInvited": "Miembro invitado",
    "memberRemoved": "Miembro eliminado",
    "memberRoleUpdated": "Rol del miembro actualizado",
    "schemeAdded": "Programa de financiación añadido",
    "schemeDeleted": "Programa de financiación eliminado",
    "holidayAdded": "Festivo añadido",
    "holidayDeleted": "Festivo eliminado",
    "departmentAdded": "Departamento añadido",
    "departmentDeleted": "Departamento eliminado",
    "approverAdded": "Aprobador añadido",
    "approverRemoved": "Aprobador eliminado",
    "periodLocked": "Período bloqueado",
    "periodUnlocked": "Período desbloqueado"
  },
  "profile": {
    "title": "Mis ajustes",
    "description": "Gestione su perfil personal, contraseña y preferencias de notificaciones por correo",
    "displayName": "Nombre para mostrar",
    "changePassword": "Cambiar contraseña",
    "currentPassword": "Contraseña actual",
    "newPassword": "Nueva contraseña",
    "confirmPassword": "Confirmar contraseña",
    "emailNotifications": "Notificaciones por correo",
    "managePreferences": "Gestione qué notificaciones por correo recibe.",
    "profileSection": "Perfil",
    "accountInfo": "Su información de cuenta",
    "organisation": "Organización",
    "passwordTooShort": "La contraseña debe tener al menos 6 caracteres.",
    "passwordMismatch": "Las contraseñas no coinciden",
    "passwordUpdated": "Contraseña actualizada correctamente",
    "profileSaved": "Perfil guardado",
    "saveProfile": "Guardar perfil",
    "updatePassword": "Cambiar contraseña",
    "updatingPassword": "Actualizando...",
    "minCharacters": "Mín. 6 caracteres",
    "reEnterPassword": "Vuelva a introducir la contraseña",
    "displayNamePlaceholder": "Su nombre para mostrar",
    "dbMigrationNote": "Las preferencias de notificación por correo requieren una migración de base de datos. Ejecute <code>supabase/add_user_preferences.sql</code> en su editor SQL de Supabase. Hasta entonces, todas las notificaciones están activadas por defecto.",
    "prefsNotAvailable": "Tabla de preferencias aún no disponible. Ejecute primero la migración SQL.",
    "couldNotSave": "No se pudo guardar — la tabla de preferencias puede no estar configurada.",
    "couldNotSavePref": "No se pudo guardar la preferencia — la tabla puede no estar configurada.",
    "languageChanged": "Idioma de la interfaz cambiado a {{language}}"
  },
  "reports": {
    "title": "Informes",
    "generateReport": "Generar informe",
    "projectSummary": "Resumen del proyecto",
    "financialReport": "Informe financiero",
    "timesheetReport": "Informe de hojas de tiempo",
    "staffAllocations": "Asignaciones de personal",
    "absenceSummary": "Resumen de ausencias",
    "reportGenerated": "Informe generado",
    "generating": "Generando..."
  },
  "guests": {
    "title": "Acceso de invitados",
    "inviteGuest": "Invitar invitado",
    "guestEmail": "Correo del invitado",
    "projectAccess": "Acceso al proyecto",
    "accessLevel": "Nivel de acceso",
    "revokeAccess": "Revocar acceso"
  },
  "audit": {
    "title": "Registro de auditoría",
    "action": "Acción",
    "entity": "Entidad",
    "user": "Usuario",
    "timestamp": "Marca de tiempo",
    "details": "Detalles"
  },
  "import": {
    "title": "Importar",
    "importData": "Importar datos",
    "selectFile": "Seleccionar archivo",
    "dragAndDrop": "Arrastre y suelte un archivo aquí",
    "supportedFormats": "Formatos admitidos: CSV, XLSX",
    "processing": "Procesando...",
    "mapping": "Mapear columnas",
    "preview": "Vista previa",
    "importComplete": "Importación completada",
    "importFailed": "Error en la importación",
    "rowsImported": "{{count}} filas importadas",
    "downloadTemplate": "Descargar plantilla",
    "step1Upload": "Subir",
    "step2Processing": "Procesando",
    "step3Map": "Mapear",
    "step4Preview": "Vista previa"
  },
  "documents": {
    "title": "Documentos",
    "uploadDocument": "Subir documento",
    "deleteDocument": "Eliminar documento",
    "deleteDocumentConfirm": "¿Eliminar \"{{name}}\"?",
    "documentUploaded": "Documento subido",
    "documentDeleted": "Documento eliminado",
    "noDocuments": "Sin documentos",
    "noDocumentsDesc": "Suba documentos del proyecto para mantener todo organizado.",
    "fileName": "Nombre del archivo",
    "fileSize": "Tamaño",
    "uploadedBy": "Subido por",
    "uploadedAt": "Subido el"
  },
  "collaboration": {
    "title": "Proyectos de colaboración",
    "description": "Gestionar proyectos de colaboración con múltiples socios",
    "newProject": "Nuevo proyecto de colaboración",
    "editProject": "Editar proyecto",
    "deleteProject": "Eliminar proyecto",
    "projectCreated": "Proyecto de colaboración creado",
    "projectUpdated": "Proyecto de colaboración actualizado",
    "projectDeleted": "Proyecto de colaboración eliminado",
    "partners": "Socios",
    "addPartner": "Añadir socio",
    "editPartner": "Editar socio",
    "deletePartner": "Eliminar socio",
    "partnerAdded": "Socio añadido",
    "partnerUpdated": "Socio actualizado",
    "partnerDeleted": "Socio eliminado",
    "contacts": "Contactos",
    "addContact": "Añadir contacto",
    "editContact": "Editar contacto",
    "deleteContact": "Eliminar contacto",
    "contactAdded": "Contacto añadido",
    "contactUpdated": "Contacto actualizado",
    "contactDeleted": "Contacto eliminado",
    "allocations": "Asignaciones",
    "tasks": "Tareas",
    "noProjects": "Aún no hay proyectos de colaboración",
    "noProjectsDesc": "Cree un proyecto de colaboración para gestionar trabajo multi-socio.",
    "totalBudget": "Presupuesto total",
    "ourShare": "Nuestra parte",
    "setup": "Configuración"
  },
  "onboarding": {
    "title": "Bienvenido a GrantLume",
    "createOrg": "Cree su organización",
    "orgNameLabel": "Nombre de la organización",
    "currencyLabel": "Moneda predeterminada",
    "letsGo": "¡Vamos!",
    "settingUp": "Configurando..."
  },
  "notifications": {
    "title": "Notificaciones",
    "markAllRead": "Marcar todo como leído",
    "noNotifications": "Sin notificaciones",
    "clearRead": "Limpiar leídas"
  },
  "topbar": {
    "mySettings": "Mis ajustes",
    "signOut": "Cerrar sesión",
    "darkMode": "Alternar modo oscuro",
    "year": "Año",
    "trialDaysRemaining": "Prueba: {{days}} días restantes",
    "member": "Miembro"
  },
  "landing": {
    "hero": "La plataforma moderna de gestión de subvenciones",
    "heroSub": "Optimice la gestión de sus proyectos financiados por la UE y fondos públicos con herramientas potentes para asignaciones, hojas de tiempo, finanzas e informes.",
    "getStarted": "Comenzar gratis",
    "viewDemo": "Ver demo",
    "trustedBy": "Confianza de organizaciones de investigación en toda Europa"
  },
  "empty": {
    "noData": "No hay datos disponibles",
    "getStarted": "Comience creando su primer elemento."
  },
  "validation": {
    "required": "Este campo es obligatorio",
    "invalidEmail": "Introduzca una dirección de correo válida",
    "minLength": "Debe tener al menos {{min}} caracteres",
    "maxLength": "Debe tener como máximo {{max}} caracteres",
    "passwordMinLength": "La contraseña debe tener al menos 8 caracteres",
    "projectNameRequired": "El nombre del proyecto es obligatorio"
  },
  "time": {
    "jan": "Ene", "feb": "Feb", "mar": "Mar", "apr": "Abr",
    "may": "May", "jun": "Jun", "jul": "Jul", "aug": "Ago",
    "sep": "Sep", "oct": "Oct", "nov": "Nov", "dec": "Dic",
    "monday": "Lunes", "tuesday": "Martes", "wednesday": "Miércoles",
    "thursday": "Jueves", "friday": "Viernes", "saturday": "Sábado", "sunday": "Domingo",
    "today": "Hoy", "yesterday": "Ayer", "tomorrow": "Mañana",
    "thisWeek": "Esta semana", "thisMonth": "Este mes", "thisYear": "Este año"
  }
};

fs.writeFileSync(path.join(localesDir, 'es.json'), JSON.stringify(es, null, 2) + '\n');
console.log('✓ es.json written');

const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));
let missing = 0;
for (const section of Object.keys(en)) {
  if (!es[section]) { console.log(`  ✗ Missing section: ${section}`); missing++; continue; }
  for (const key of Object.keys(en[section])) {
    if (typeof en[section][key] === 'object') {
      if (!es[section][key]) { console.log(`  ✗ Missing nested: ${section}.${key}`); missing++; continue; }
      for (const subkey of Object.keys(en[section][key])) {
        if (es[section][key][subkey] === undefined) { console.log(`  ✗ Missing: ${section}.${key}.${subkey}`); missing++; }
      }
    } else {
      if (es[section][key] === undefined) { console.log(`  ✗ Missing: ${section}.${key}`); missing++; }
    }
  }
}
if (missing === 0) console.log('✓ All keys present in es.json');
else console.log(`✗ ${missing} missing key(s)`);
