const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '..', 'src', 'locales');

const fr = {
  "nav": {
    "core": "Principal",
    "operations": "Opérations",
    "administration": "Administration",
    "dashboard": "Tableau de bord",
    "projects": "Nos Projets",
    "proposals": "Propositions",
    "staff": "Personnel",
    "allocations": "Allocations",
    "timesheets": "Feuilles de temps",
    "absences": "Absences",
    "financials": "Finances",
    "timeline": "Chronologie",
    "reports": "Rapports",
    "import": "Import",
    "auditLog": "Journal d'audit",
    "collaboration": "Collaboration",
    "settings": "Paramètres",
    "projectOverview": "Vue d'ensemble du projet",
    "help": "Aide & FAQ"
  },
  "common": {
    "save": "Enregistrer",
    "cancel": "Annuler",
    "delete": "Supprimer",
    "edit": "Modifier",
    "create": "Créer",
    "add": "Ajouter",
    "remove": "Retirer",
    "close": "Fermer",
    "confirm": "Confirmer",
    "back": "Retour",
    "next": "Suivant",
    "search": "Rechercher",
    "filter": "Filtrer",
    "export": "Exporter",
    "loading": "Chargement...",
    "saving": "Enregistrement...",
    "deleting": "Suppression...",
    "noResults": "Aucun résultat trouvé",
    "error": "Erreur",
    "success": "Succès",
    "warning": "Avertissement",
    "actions": "Actions",
    "status": "Statut",
    "name": "Nom",
    "email": "E-mail",
    "role": "Rôle",
    "date": "Date",
    "type": "Type",
    "description": "Description",
    "notes": "Notes",
    "total": "Total",
    "active": "Actif",
    "inactive": "Inactif",
    "all": "Tous",
    "yes": "Oui",
    "no": "Non",
    "or": "ou",
    "and": "et",
    "of": "de",
    "to": "à",
    "from": "de",
    "submit": "Soumettre",
    "approve": "Approuver",
    "reject": "Rejeter",
    "pending": "En attente",
    "approved": "Approuvé",
    "rejected": "Rejeté",
    "download": "Télécharger",
    "upload": "Téléverser",
    "refresh": "Actualiser",
    "reset": "Réinitialiser",
    "selectAll": "Tout sélectionner",
    "deselectAll": "Tout désélectionner",
    "showing": "Affichage",
    "items": "éléments",
    "page": "Page",
    "previous": "Précédent",
    "rows": "lignes",
    "columns": "Colonnes",
    "viewAll": "Voir tout",
    "learnMore": "En savoir plus",
    "required": "Obligatoire",
    "optional": "Optionnel",
    "synced": "Synchronisé",
    "upToDate": "À jour",
    "syncing": "Synchronisation...",
    "computing": "Calcul...",
    "adding": "Ajout...",
    "updating": "Mise à jour...",
    "project": "Projet",
    "projects": "projets",
    "budget": "Budget",
    "actual": "Réel",
    "remaining": "Restant",
    "over": "Dépassement",
    "period": "Période",
    "title": "Titre",
    "acronym": "Acronyme",
    "scheme": "Programme",
    "lead": "Responsable",
    "programme": "Programme",
    "partners": "Partenaires",
    "searchPlaceholder": "Rechercher par acronyme ou titre...",
    "noProjectsFound": "Aucun projet trouvé",
    "tryAdjusting": "Essayez d'ajuster votre recherche.",
    "createFirstProject": "Créez votre premier projet pour commencer.",
    "showingCount": "{{count}} projet(s) affiché(s)",
    "deleteProject": "Supprimer le projet",
    "deleteProjectConfirm": "Êtes-vous sûr de vouloir supprimer \"{{name}}\" ? Tous les lots de travail, allocations et feuilles de temps associés seront également supprimés.",
    "deleted": "Supprimé",
    "hasBeenRemoved": "{{name}} a été supprimé.",
    "failedToDelete": "Échec de la suppression",
    "failedToSave": "Échec de l'enregistrement",
    "suspended": "Suspendu",
    "upcoming": "À venir",
    "none": "Aucun",
    "member": "Membre",
    "person": "Personne",
    "amount": "Montant",
    "vendor": "Fournisseur",
    "reference": "Référence",
    "category": "Catégorie",
    "update": "Mettre à jour",
    "record": "Enregistrer",
    "invited": "Invité",
    "account": "Compte",
    "overBudget": "Dépassement de budget",
    "noneSelected": "— Aucun —",
    "ref": "Réf : {{ref}}",
    "countItems": "{{count}} {{item}}",
    "allCategories": "Toutes les catégories",
    "exportPdf": "Exporter en PDF"
  },
  "auth": {
    "login": "Connexion",
    "logout": "Déconnexion",
    "signUp": "S'inscrire",
    "signIn": "Se connecter",
    "forgotPassword": "Mot de passe oublié ?",
    "resetPassword": "Réinitialiser le mot de passe",
    "setNewPassword": "Définir un nouveau mot de passe",
    "email": "E-mail",
    "password": "Mot de passe",
    "confirmPassword": "Confirmer le mot de passe",
    "firstName": "Prénom",
    "lastName": "Nom",
    "rememberMe": "Rester connecté",
    "createAccount": "Créer votre compte",
    "alreadyHaveAccount": "Vous avez déjà un compte ?",
    "dontHaveAccount": "Pas encore de compte ?",
    "termsAgree": "En cliquant, vous confirmez avoir lu et accepté les",
    "termsOfUse": "Conditions d'utilisation",
    "privacyPolicy": "Politique de confidentialité",
    "startTrial": "Essai gratuit de 14 jours",
    "noPaymentRequired": "Aucune information de paiement requise",
    "startUsingImmediately": "Commencez à utiliser GrantLume immédiatement",
    "noInstallation": "Aucune installation",
    "cloudBased": "Cloud — fonctionne dans votre navigateur",
    "trialAutoEnds": "La période d'essai de 14 jours se termine automatiquement",
    "noObligations": "Sans engagement, annulez à tout moment",
    "registerFree": "S'inscrire gratuitement",
    "startFreeTrial": "Commencez votre essai gratuit de 14 jours — aucune carte de crédit requise",
    "creatingAccount": "Création du compte...",
    "checkYourEmail": "Vérifiez votre e-mail",
    "confirmationSent": "Nous avons envoyé un lien de confirmation à",
    "clickToActivate": "Cliquez sur le lien pour activer votre compte et commencer votre essai gratuit de 14 jours.",
    "didntReceive": "Vous n'avez pas reçu l'e-mail ? Vérifiez votre dossier spam ou attendez quelques minutes.",
    "resendConfirmation": "Renvoyer l'e-mail de confirmation",
    "goToLogin": "Aller à la connexion",
    "passwordStrength": "Force du mot de passe",
    "weak": "Faible",
    "fair": "Moyen",
    "good": "Bon",
    "strong": "Fort",
    "passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
    "accountRecovery": "Récupération de compte",
    "wellHelpYouBack": "Nous vous aiderons à retrouver l'accès à votre compte",
    "sendResetLink": "Envoyer le lien",
    "sendingResetLink": "Envoi...",
    "resetLinkSent": "Vérifiez votre e-mail",
    "resetLinkSentDesc": "Si un compte existe pour cet e-mail, vous recevrez un lien de réinitialisation.",
    "backToLogin": "Retour à la connexion",
    "chooseStrongPassword": "Choisissez un mot de passe fort et unique",
    "newPassword": "Nouveau mot de passe",
    "updatePassword": "Mettre à jour le mot de passe",
    "updatingPassword": "Mise à jour...",
    "passwordUpdated": "Mot de passe mis à jour",
    "canNowSignIn": "Vous pouvez maintenant vous connecter avec votre nouveau mot de passe",
    "securityCheck": "Vérification de sécurité",
    "solveToProve": "Résolvez ceci pour prouver que vous êtes humain",
    "tooManyAttempts": "Trop de tentatives échouées. Réessayez plus tard."
  },
  "callback": {
    "verifying": "Vérification...",
    "pleaseWait": "Veuillez patienter pendant que nous confirmons votre compte",
    "emailConfirmed": "E-mail confirmé !",
    "accountVerified": "Votre compte a été vérifié avec succès. Vous êtes prêt à configurer votre organisation et à gérer vos projets de financement.",
    "whatsNext": "Et ensuite ?",
    "step1": "Créez votre organisation",
    "step2": "Ajoutez votre premier projet",
    "step3": "Invitez vos membres d'équipe",
    "continueToSetup": "Continuer la configuration",
    "youreAllSet": "Tout est prêt !",
    "verifiedRedirecting": "Vérifié ! Redirection...",
    "verificationFailed": "Échec de la vérification",
    "linkExpired": "Impossible de vérifier votre e-mail. Le lien a peut-être expiré ou a déjà été utilisé. Veuillez essayer de vous connecter."
  },
  "dashboard": {
    "title": "Tableau de bord",
    "welcome": "Bon retour",
    "overview": "Vue d'ensemble",
    "activeProjects": "Projets actifs",
    "totalStaff": "Personnel total",
    "pendingTimesheets": "Feuilles de temps en attente",
    "upcomingDeadlines": "Échéances à venir",
    "recentActivity": "Activité récente",
    "quickActions": "Actions rapides",
    "budgetOverview": "Aperçu du budget",
    "projectStatus": "Statut du projet",
    "portfolioOverview": "Aperçu du portefeuille — {{year}}",
    "kpiProjects": "Projets",
    "kpiStaff": "Personnel",
    "kpiTotalBudget": "Budget total",
    "kpiPersonMonths": "Personne-mois",
    "kpiProposals": "Propositions",
    "kpiCollaborations": "Collaborations",
    "activeCount": "{{count}} actif(s)",
    "submittedCount": "{{count}} soumis",
    "acrossAllProjects": "tous projets confondus",
    "actualIn": "réel en {{year}}",
    "plannedIn": "prévu en {{year}}",
    "projectsEndingSoon": "{{count}} projet(s) se terminant bientôt : {{names}}",
    "staffOverAllocated": "{{count}} membre(s) du personnel suralloué(s) cette année",
    "monthlyAllocations": "Allocations mensuelles (PM)",
    "projectStatusDistribution": "Distribution des statuts de projet",
    "noProjectsYet": "Pas encore de projets",
    "projectsOverview": "Aperçu des projets",
    "pmsYear": "PM ({{year}})"
  },
  "projects": {
    "title": "Nos Projets",
    "description": "La part de votre organisation dans chaque projet",
    "newProject": "Nouveau projet",
    "editProject": "Modifier le projet",
    "importWithAI": "Importer avec l'IA",
    "projectDetails": "Détails du projet",
    "acronym": "Acronyme",
    "fullTitle": "Titre complet",
    "startDate": "Date de début",
    "endDate": "Date de fin",
    "fundingScheme": "Programme de financement",
    "budget": "Budget",
    "responsiblePerson": "Personne responsable",
    "workPackages": "Lots de travail",
    "deliverables": "Livrables",
    "milestones": "Jalons",
    "personnel": "Personnel",
    "documents": "Documents",
    "expenses": "Dépenses",
    "noProjects": "Pas encore de projets",
    "noProjectsDesc": "Créez votre premier projet pour commencer.",
    "status": "Statut",
    "active": "Actif",
    "completed": "Terminé",
    "preparation": "En préparation",
    "pmRate": "Taux PM",
    "totalBudget": "Budget total",
    "spentBudget": "Dépensé",
    "remainingBudget": "Restant",
    "collaboration": "Collaboration",
    "collaborationProjects": "Projets de collaboration",
    "notFound": "Projet non trouvé",
    "backToProjects": "Retour aux projets",
    "overview": "Vue d'ensemble",
    "reporting": "Rapports",
    "grantNumber": "Numéro de subvention",
    "ledByOurOrg": "Dirigé par notre organisation",
    "budgetBreakdown": "Ventilation du budget",
    "travel": "Voyages",
    "subcontracting": "Sous-traitance",
    "other": "Autres",
    "otherDirectCosts": "Autres coûts directs",
    "indirectCosts": "Coûts indirects",
    "overheadRate": "Taux de frais généraux",
    "ourPmRate": "Notre taux PM",
    "personMonthsPerYear": "Personne-mois par an",
    "totalAcrossYears": "Total sur toutes les années",
    "assignedToWPs": "Assigné aux LT",
    "ofBudget": "du budget",
    "allocated": "Alloué",
    "peopleAllocated": "Personnes allouées au projet",
    "remaining": "Restant",
    "budgetMinusAllocated": "Budget moins alloué",
    "projectBudget": "Budget du projet",
    "pmBudgetDistribution": "Distribution du budget PM",
    "unassigned": "Non assigné",
    "addWorkPackage": "Ajouter un lot de travail",
    "wpNumber": "LT #",
    "wpName": "Nom",
    "wpDescription": "Description",
    "startMonth": "Mois de début",
    "endMonth": "Mois de fin",
    "addWP": "Ajouter LT",
    "wpAdded": "Lot de travail ajouté",
    "wpDeleted": "Lot de travail supprimé",
    "wpUpdated": "Lot de travail mis à jour.",
    "deleteWP": "Supprimer le lot de travail",
    "deleteWPConfirm": "Êtes-vous sûr de vouloir supprimer \"{{name}}\" ?",
    "budgetPM": "Budget PM",
    "savePmBudgets": "Enregistrer les budgets PM",
    "pmBudgetsUpdated": "Budgets PM mis à jour.",
    "wpPmBudgetsUpdated": "Budgets PM des LT mis à jour.",
    "projectDuration": "Durée du projet : {{months}} mois ({{start}} – {{end}})"
  },
  "expenses": {
    "title": "Dépenses",
    "recordExpense": "Enregistrer une dépense",
    "editExpense": "Modifier la dépense",
    "deleteExpense": "Supprimer la dépense",
    "deleteExpenseConfirm": "Supprimer \"{{name}}\" ({{amount}}) ?",
    "expenseRecorded": "Dépense enregistrée",
    "expenseUpdated": "Dépense mise à jour",
    "expenseDeleted": "Dépense supprimée",
    "invalidAmount": "Montant invalide",
    "noExpenses": "Aucune dépense enregistrée",
    "noExpensesDesc": "Enregistrez les dépenses du projet pour suivre la consommation budgétaire pour les voyages, la sous-traitance et autres catégories de coûts.",
    "spent": "Dépensé",
    "budgetForCategory": "Budget pour {{category}} :",
    "afterThisExpense": "Après cette dépense :",
    "remainingAfter": "{{amount}} restant",
    "overBudgetAfter": "{{amount}} de dépassement",
    "budgetAlertMessage": "Le budget {{category}} est consommé à {{spentPct}}% mais seulement {{timelinePct}}% de la durée du projet s'est écoulée.",
    "descriptionPlaceholder": "Ex. Vol vers Bruxelles pour réunion de consortium",
    "vendorPlaceholder": "Ex. Air France, Hôtel Bruxelles",
    "referencePlaceholder": "Ex. FACT-2026-001",
    "additionalDetails": "Détails supplémentaires...",
    "vendorPayee": "Fournisseur / Bénéficiaire",
    "referenceInvoice": "Référence / N° de facture",
    "expenseCount": "{{count}} dépense",
    "expenseCountPlural": "{{count}} dépenses"
  },
  "deliverables": {
    "title": "Livrables",
    "addDeliverable": "Ajouter un livrable",
    "editDeliverable": "Modifier le livrable",
    "deleteDeliverable": "Supprimer le livrable",
    "deleteDeliverableConfirm": "Supprimer le livrable \"{{name}}\" ?",
    "deliverableAdded": "Livrable ajouté",
    "deliverableUpdated": "Livrable mis à jour",
    "deliverableDeleted": "Livrable supprimé",
    "noDeliverables": "Aucun livrable",
    "noDeliverablesDesc": "Ajoutez des livrables au projet pour suivre les résultats et les échéances.",
    "number": "Numéro",
    "dueMonth": "Mois d'échéance",
    "workPackage": "Lot de travail",
    "addMilestone": "Ajouter un jalon",
    "editMilestone": "Modifier le jalon",
    "deleteMilestone": "Supprimer le jalon",
    "deleteMilestoneConfirm": "Supprimer le jalon \"{{name}}\" ?",
    "milestoneAdded": "Jalon ajouté",
    "milestoneUpdated": "Jalon mis à jour",
    "milestoneDeleted": "Jalon supprimé",
    "noMilestones": "Aucun jalon",
    "noMilestonesDesc": "Ajoutez des jalons au projet pour suivre les réalisations clés.",
    "verificationMeans": "Moyens de vérification"
  },
  "reporting": {
    "title": "Périodes de rapport",
    "addPeriod": "Ajouter une période",
    "editPeriod": "Modifier la période",
    "deletePeriod": "Supprimer la période",
    "deletePeriodConfirm": "Supprimer la période de rapport #{{number}} ?",
    "periodAdded": "Période de rapport ajoutée",
    "periodUpdated": "Période de rapport mise à jour",
    "periodDeleted": "Période de rapport supprimée",
    "noPeriods": "Aucune période de rapport",
    "noPeriodsDesc": "Ajoutez des périodes de rapport pour suivre les échéances de revue.",
    "periodNumber": "Période #",
    "technicalReportDue": "Rapport technique dû",
    "financialReportDue": "Rapport financier dû"
  },
  "budgetChart": {
    "title": "Consommation budgétaire",
    "budgeted": "Budgété",
    "actual": "Réel",
    "percentUsed": "{{percent}}% utilisé",
    "noData": "Aucune donnée budgétaire disponible pour ce projet.",
    "timeElapsed": "{{percent}}% du temps du projet écoulé",
    "overSpending": "Les dépenses dépassent le calendrier",
    "underSpending": "Les dépenses sont dans les temps",
    "categories": {
      "personnel": "Personnel",
      "travel": "Voyages",
      "subcontracting": "Sous-traitance",
      "other": "Autres",
      "indirect": "Indirect"
    }
  },
  "staff": {
    "title": "Personnel",
    "addPerson": "Ajouter une personne",
    "editPerson": "Modifier la personne",
    "fullName": "Nom complet",
    "department": "Département",
    "role": "Rôle",
    "employmentType": "Type d'emploi",
    "fte": "ETP",
    "startDate": "Date de début",
    "endDate": "Date de fin",
    "salary": "Salaire annuel",
    "vacationDays": "Jours de congé",
    "country": "Pays",
    "isActive": "Actif",
    "noStaff": "Pas encore de personnel",
    "noStaffDesc": "Ajoutez votre premier membre d'équipe pour commencer.",
    "inviteToSystem": "Inviter sur GrantLume",
    "accountStatus": "Statut du compte",
    "sendInvitation": "Envoyer l'invitation",
    "resendInvitation": "Renvoyer l'invitation",
    "personCreated": "Personne créée",
    "personUpdated": "Personne mise à jour",
    "personDeleted": "Personne supprimée",
    "deletePerson": "Supprimer la personne",
    "deletePersonConfirm": "Êtes-vous sûr de vouloir supprimer \"{{name}}\" ?",
    "searchPlaceholder": "Rechercher du personnel...",
    "leaveBalance": "Solde de congés",
    "leaveUsed": "{{used}} / {{total}} jours utilisés",
    "overheadRate": "Taux de frais généraux",
    "phone": "Téléphone",
    "avatar": "Avatar",
    "uploadAvatar": "Téléverser l'avatar",
    "removeAvatar": "Supprimer l'avatar",
    "personalInfo": "Informations personnelles",
    "employmentDetails": "Détails de l'emploi",
    "financialInfo": "Informations financières",
    "invitationSent": "Invitation envoyée",
    "invitationResent": "Invitation renvoyée",
    "invitingUser": "Invitation en cours...",
    "systemRole": "Rôle système",
    "projectsInvolved": "Projets impliqués"
  },
  "allocations": {
    "title": "Allocations",
    "description": "Gérer les allocations de personne-mois entre les projets",
    "personMonth": "Personne-mois",
    "personMonths": "Personne-mois",
    "pm": "PM",
    "capacity": "Capacité",
    "overAllocated": "Suralloué",
    "unsavedChanges": "Modifications non enregistrées",
    "pmBudgets": "Budgets PM",
    "bulkFill": "Remplissage en masse",
    "addRow": "Ajouter une ligne",
    "undo": "Annuler",
    "redo": "Rétablir",
    "allocationGrid": "Grille d'allocation",
    "personnelOverview": "Aperçu du personnel",
    "projectOverview": "Aperçu du projet",
    "periodLocks": "Verrouillages de période",
    "saved": "Allocations enregistrées",
    "selectPerson": "Sélectionner une personne",
    "selectProject": "Sélectionner un projet",
    "selectWorkPackage": "Sélectionner un lot de travail"
  },
  "timesheets": {
    "title": "Feuilles de temps",
    "myTimesheet": "Ma feuille de temps",
    "allTimesheets": "Toutes les feuilles de temps",
    "submitTimesheet": "Soumettre la feuille de temps",
    "approveTimesheets": "Approuver les feuilles de temps",
    "hours": "Heures",
    "totalHours": "Total des heures",
    "period": "Période",
    "submitted": "Soumis",
    "draft": "Brouillon",
    "noEntries": "Pas encore de saisies",
    "noEntriesDesc": "Commencez à enregistrer vos heures pour cette période.",
    "weeklyView": "Vue hebdomadaire",
    "monthlyView": "Vue mensuelle",
    "timesheetSubmitted": "Feuille de temps soumise",
    "timesheetApproved": "Feuille de temps approuvée",
    "timesheetRejected": "Feuille de temps rejetée",
    "timesheetSaved": "Feuille de temps enregistrée",
    "submitConfirm": "Soumettre cette feuille de temps ? Une fois soumise, elle ne pourra plus être modifiée jusqu'à sa révision.",
    "workingDay": "Jour ouvré",
    "weekend": "Week-end",
    "holiday": "Jour férié",
    "selectMonth": "Sélectionner le mois",
    "noTimesheetData": "Aucune donnée de feuille de temps",
    "noTimesheetDataDesc": "Aucune saisie trouvée pour cette période."
  },
  "absences": {
    "title": "Absences",
    "description": "Suivre les absences et congés du personnel",
    "newAbsence": "Nouvelle absence",
    "editAbsence": "Modifier l'absence",
    "deleteAbsence": "Supprimer l'absence",
    "deleteAbsenceConfirm": "Supprimer cette absence ?",
    "absenceType": "Type d'absence",
    "vacation": "Congé",
    "sickLeave": "Arrêt maladie",
    "publicHoliday": "Jour férié",
    "training": "Formation",
    "conference": "Conférence",
    "other": "Autre",
    "startDate": "Date de début",
    "endDate": "Date de fin",
    "days": "Jours",
    "halfDay": "Demi-journée",
    "reason": "Motif",
    "noAbsences": "Aucune absence enregistrée",
    "noAbsencesDesc": "Enregistrez les absences pour suivre la disponibilité de l'équipe.",
    "approvers": "Approbateurs",
    "myAbsences": "Mes absences",
    "teamAbsences": "Absences de l'équipe",
    "timeline": "Chronologie",
    "listView": "Vue liste",
    "absenceCreated": "Absence enregistrée",
    "absenceUpdated": "Absence mise à jour",
    "absenceDeleted": "Absence supprimée",
    "absenceApproved": "Absence approuvée",
    "absenceRejected": "Absence rejetée",
    "substitute": "Remplaçant",
    "selectPerson": "Sélectionner une personne",
    "daysCount": "{{count}} jour(s)"
  },
  "financials": {
    "title": "Finances",
    "description": "Suivi budget vs réel pour {{year}}",
    "budgetOverview": "Aperçu du budget",
    "enterActuals": "Saisir les réels",
    "expenses": "Dépenses",
    "category": "Catégorie",
    "amount": "Montant",
    "personnelBudget": "Personnel",
    "travelBudget": "Voyages",
    "subcontractingBudget": "Sous-traitance",
    "otherBudget": "Autres directs",
    "indirectCosts": "Coûts indirects",
    "totalBudget": "Budget total",
    "spent": "Dépensé",
    "remaining": "Restant",
    "utilization": "Utilisation",
    "syncBudgets": "Synchroniser les budgets depuis les projets",
    "computePersonnel": "Calculer les réels personnel",
    "syncExpenses": "Synchroniser les réels dépenses",
    "noFinancialData": "Aucune donnée financière",
    "noFinancialDataDesc": "Ajoutez des projets et des entrées budgétaires pour voir l'aperçu budget vs réel.",
    "budgetRowsUpToDate": "Toutes les lignes budgétaires sont à jour et synchronisées avec les données du projet.",
    "budgetRowsSynced": "Lignes budgétaires : {{details}}.",
    "created": "créé",
    "updated": "mis à jour",
    "personnelUpToDate": "Les réels personnel correspondent déjà aux données d'allocation.",
    "personnelSynced": "{{count}} réel(s) personnel mis à jour depuis les données d'allocation.",
    "expensesUpToDate": "Les réels non-personnel correspondent déjà aux enregistrements de dépenses.",
    "expensesSynced": "{{count}} réel(s) budgétaire(s) mis à jour depuis les enregistrements de dépenses.",
    "under80": "Moins de 80%",
    "between80and100": "80–100%",
    "overBudget": "Dépassement",
    "grandTotal": "TOTAL",
    "actualsSaved": "Réels enregistrés"
  },
  "proposals": {
    "title": "Propositions",
    "description": "Suivre les demandes de subvention et convertir les acceptées en projets",
    "newProposal": "Nouvelle proposition",
    "editProposal": "Modifier la proposition",
    "deleteProposal": "Supprimer la proposition",
    "deleteProposalConfirm": "Êtes-vous sûr de vouloir supprimer \"{{name}}\" ? Cette action est irréversible.",
    "proposalCreated": "Proposition créée",
    "proposalUpdated": "Proposition mise à jour",
    "proposalDeleted": "Proposition supprimée",
    "projectName": "Nom du projet",
    "callIdentifier": "Identifiant d'appel",
    "fundingScheme": "Programme de financement",
    "submissionDeadline": "Date limite de soumission",
    "expectedDecision": "Décision attendue",
    "approxDecisionDate": "Date de décision approximative",
    "ourPms": "Nos PMs",
    "inPreparation": "En préparation",
    "submitted": "Soumis",
    "granted": "Accordé",
    "rejected": "Rejeté",
    "convertToProject": "Convertir en projet",
    "convertToProjectConfirm": "Cela créera un nouveau projet à partir de \"{{name}}\" avec les données budgétaires de la proposition. Vous pourrez ensuite modifier les détails du projet. Continuer ?",
    "projectCreated": "Projet créé !",
    "projectCreatedDesc": "Redirection vers le nouveau projet...",
    "converting": "Conversion...",
    "createProject": "Créer le projet",
    "pipeline": "Pipeline",
    "noProposals": "Pas encore de propositions",
    "noProposalsDesc": "Suivez vos propositions de subvention de la soumission à la décision.",
    "addFirstProposal": "Ajoutez votre première proposition",
    "allProposals": "Toutes les propositions",
    "filteredProposals": "Propositions {{status}}",
    "budgetBreakdown": "Ventilation du budget",
    "personnelBudget": "Budget personnel",
    "travelBudget": "Budget voyages",
    "subcontractingBudget": "Budget sous-traitance",
    "otherBudget": "Autre budget",
    "totalBudget": "Budget total",
    "responsiblePerson": "Personne responsable",
    "updateProposal": "Mettre à jour la proposition",
    "createProposal": "Créer la proposition",
    "enterDetails": "Saisissez les détails de votre demande de subvention.",
    "updateDetails": "Mettez à jour les détails de la proposition.",
    "searchEuCalls": "Rechercher des appels UE ou saisir un identifiant...",
    "searchEuCallsHint": "Commencez à taper pour rechercher des appels ouverts EU Funding & Tenders, ou saisissez un identifiant",
    "selectFundingScheme": "Sélectionner ou saisir un programme de financement...",
    "noMatchingSchemes": "Aucun programme correspondant — saisissez un personnalisé",
    "goToProject": "Aller au projet"
  },
  "settings": {
    "title": "Paramètres",
    "description": "Paramètres et configuration de l'organisation",
    "organisation": "Organisation",
    "orgName": "Nom de l'organisation",
    "currency": "Devise",
    "workingHours": "Heures de travail par jour",
    "departments": "Départements",
    "users": "Utilisateurs",
    "members": "Membres de l'organisation",
    "addMember": "Ajouter un membre",
    "removeMember": "Retirer un membre",
    "rolePermissions": "Permissions des rôles",
    "fundingSchemes": "Programmes de financement",
    "holidays": "Jours fériés",
    "periodLocking": "Verrouillage de période",
    "language": "Langue",
    "selectLanguage": "Sélectionner la langue",
    "languageDesc": "Choisissez votre langue d'interface préférée. Ce paramètre est enregistré dans votre profil.",
    "general": "Général",
    "dangerZone": "Zone de danger",
    "absenceApprovers": "Approbateurs d'absences",
    "absenceTypes": "Types d'absences",
    "rolePermDesc": "Configurez ce que chaque rôle peut voir et faire. Les administrateurs ont toujours un accès complet. Les participants externes ne peuvent accéder qu'aux projets auxquels ils sont invités.",
    "moduleVisibility": "Visibilité des modules",
    "whichSections": "Quelles sections apparaissent dans la barre latérale",
    "sensitiveData": "Données sensibles",
    "accessConfidential": "Accès aux informations confidentielles",
    "actionsLabel": "Actions",
    "whatRoleCanDo": "Ce que ce rôle peut créer, modifier ou gérer",
    "adminNote": "Le rôle d'administrateur a toujours un accès complet à tous les modules et données. Les modifications ci-dessous s'appliquent uniquement aux utilisateurs <strong>{{role}}</strong>.",
    "resetToDefaults": "Réinitialiser",
    "saveChanges": "Enregistrer les modifications",
    "resetConfirm": "Réinitialiser les permissions de \"{{role}}\" ?\n\nCela annulera toutes les personnalisations pour ce rôle.",
    "permissionsSaved": "Permissions des rôles mises à jour. Les utilisateurs verront les changements à la prochaine connexion.",
    "settingsSaved": "Paramètres enregistrés",
    "memberInvited": "Membre invité",
    "memberRemoved": "Membre retiré",
    "memberRoleUpdated": "Rôle du membre mis à jour",
    "schemeAdded": "Programme de financement ajouté",
    "schemeDeleted": "Programme de financement supprimé",
    "holidayAdded": "Jour férié ajouté",
    "holidayDeleted": "Jour férié supprimé",
    "departmentAdded": "Département ajouté",
    "departmentDeleted": "Département supprimé",
    "approverAdded": "Approbateur ajouté",
    "approverRemoved": "Approbateur retiré",
    "periodLocked": "Période verrouillée",
    "periodUnlocked": "Période déverrouillée"
  },
  "profile": {
    "title": "Mes paramètres",
    "description": "Gérez votre profil, mot de passe et préférences de notification par e-mail",
    "displayName": "Nom d'affichage",
    "changePassword": "Changer le mot de passe",
    "currentPassword": "Mot de passe actuel",
    "newPassword": "Nouveau mot de passe",
    "confirmPassword": "Confirmer le mot de passe",
    "emailNotifications": "Notifications par e-mail",
    "managePreferences": "Gérez les notifications par e-mail que vous recevez.",
    "profileSection": "Profil",
    "accountInfo": "Vos informations de compte",
    "organisation": "Organisation",
    "passwordTooShort": "Le mot de passe doit comporter au moins 6 caractères.",
    "passwordMismatch": "Les mots de passe ne correspondent pas",
    "passwordUpdated": "Mot de passe mis à jour avec succès",
    "profileSaved": "Profil enregistré",
    "saveProfile": "Enregistrer le profil",
    "updatePassword": "Changer le mot de passe",
    "updatingPassword": "Mise à jour...",
    "minCharacters": "Min. 6 caractères",
    "reEnterPassword": "Ressaisir le mot de passe",
    "displayNamePlaceholder": "Votre nom d'affichage",
    "dbMigrationNote": "Les préférences de notification par e-mail nécessitent une migration de base de données. Exécutez <code>supabase/add_user_preferences.sql</code> dans votre éditeur SQL Supabase. En attendant, toutes les notifications sont activées par défaut.",
    "prefsNotAvailable": "Table des préférences pas encore disponible. Exécutez d'abord la migration SQL.",
    "couldNotSave": "Impossible d'enregistrer — la table des préférences n'est peut-être pas configurée.",
    "couldNotSavePref": "Impossible d'enregistrer la préférence — la table n'est peut-être pas configurée.",
    "languageChanged": "Langue de l'interface changée en {{language}}"
  },
  "reports": {
    "title": "Rapports",
    "generateReport": "Générer un rapport",
    "projectSummary": "Résumé du projet",
    "financialReport": "Rapport financier",
    "timesheetReport": "Rapport des feuilles de temps",
    "staffAllocations": "Allocations du personnel",
    "absenceSummary": "Résumé des absences",
    "reportGenerated": "Rapport généré",
    "generating": "Génération..."
  },
  "guests": {
    "title": "Accès invité",
    "inviteGuest": "Inviter un invité",
    "guestEmail": "E-mail de l'invité",
    "projectAccess": "Accès au projet",
    "accessLevel": "Niveau d'accès",
    "revokeAccess": "Révoquer l'accès"
  },
  "audit": {
    "title": "Journal d'audit",
    "action": "Action",
    "entity": "Entité",
    "user": "Utilisateur",
    "timestamp": "Horodatage",
    "details": "Détails"
  },
  "import": {
    "title": "Import",
    "importData": "Importer des données",
    "selectFile": "Sélectionner un fichier",
    "dragAndDrop": "Glissez-déposez un fichier ici",
    "supportedFormats": "Formats pris en charge : CSV, XLSX",
    "processing": "Traitement...",
    "mapping": "Mapper les colonnes",
    "preview": "Aperçu",
    "importComplete": "Import terminé",
    "importFailed": "Échec de l'import",
    "rowsImported": "{{count}} lignes importées",
    "downloadTemplate": "Télécharger le modèle",
    "step1Upload": "Téléverser",
    "step2Processing": "Traitement",
    "step3Map": "Mapper",
    "step4Preview": "Aperçu"
  },
  "documents": {
    "title": "Documents",
    "uploadDocument": "Téléverser un document",
    "deleteDocument": "Supprimer le document",
    "deleteDocumentConfirm": "Supprimer \"{{name}}\" ?",
    "documentUploaded": "Document téléversé",
    "documentDeleted": "Document supprimé",
    "noDocuments": "Aucun document",
    "noDocumentsDesc": "Téléversez des documents de projet pour tout garder organisé.",
    "fileName": "Nom du fichier",
    "fileSize": "Taille",
    "uploadedBy": "Téléversé par",
    "uploadedAt": "Téléversé le"
  },
  "collaboration": {
    "title": "Projets de collaboration",
    "description": "Gérer les projets de collaboration multi-partenaires",
    "newProject": "Nouveau projet de collaboration",
    "editProject": "Modifier le projet",
    "deleteProject": "Supprimer le projet",
    "projectCreated": "Projet de collaboration créé",
    "projectUpdated": "Projet de collaboration mis à jour",
    "projectDeleted": "Projet de collaboration supprimé",
    "partners": "Partenaires",
    "addPartner": "Ajouter un partenaire",
    "editPartner": "Modifier le partenaire",
    "deletePartner": "Supprimer le partenaire",
    "partnerAdded": "Partenaire ajouté",
    "partnerUpdated": "Partenaire mis à jour",
    "partnerDeleted": "Partenaire supprimé",
    "contacts": "Contacts",
    "addContact": "Ajouter un contact",
    "editContact": "Modifier le contact",
    "deleteContact": "Supprimer le contact",
    "contactAdded": "Contact ajouté",
    "contactUpdated": "Contact mis à jour",
    "contactDeleted": "Contact supprimé",
    "allocations": "Allocations",
    "tasks": "Tâches",
    "noProjects": "Pas encore de projets de collaboration",
    "noProjectsDesc": "Créez un projet de collaboration pour gérer le travail multi-partenaires.",
    "totalBudget": "Budget total",
    "ourShare": "Notre part",
    "setup": "Configuration"
  },
  "onboarding": {
    "title": "Bienvenue sur GrantLume",
    "createOrg": "Créez votre organisation",
    "orgNameLabel": "Nom de l'organisation",
    "currencyLabel": "Devise par défaut",
    "letsGo": "C'est parti !",
    "settingUp": "Configuration en cours..."
  },
  "notifications": {
    "title": "Notifications",
    "markAllRead": "Tout marquer comme lu",
    "noNotifications": "Aucune notification",
    "clearRead": "Effacer les lues"
  },
  "topbar": {
    "mySettings": "Mes paramètres",
    "signOut": "Se déconnecter",
    "darkMode": "Basculer le mode sombre",
    "year": "Année",
    "trialDaysRemaining": "Essai : {{days}} jours restants",
    "member": "Membre"
  },
  "landing": {
    "hero": "La plateforme moderne de gestion de subventions",
    "heroSub": "Optimisez la gestion de vos projets financés par l'UE et les fonds publics avec des outils puissants pour les allocations, les feuilles de temps, les finances et les rapports.",
    "getStarted": "Commencer gratuitement",
    "viewDemo": "Voir la démo",
    "trustedBy": "Approuvé par les organismes de recherche à travers l'Europe"
  },
  "empty": {
    "noData": "Aucune donnée disponible",
    "getStarted": "Commencez par créer votre premier élément."
  },
  "validation": {
    "required": "Ce champ est obligatoire",
    "invalidEmail": "Veuillez saisir une adresse e-mail valide",
    "minLength": "Doit comporter au moins {{min}} caractères",
    "maxLength": "Doit comporter au plus {{max}} caractères",
    "passwordMinLength": "Le mot de passe doit comporter au moins 8 caractères",
    "projectNameRequired": "Le nom du projet est obligatoire"
  },
  "time": {
    "jan": "Janv", "feb": "Févr", "mar": "Mars", "apr": "Avr",
    "may": "Mai", "jun": "Juin", "jul": "Juil", "aug": "Août",
    "sep": "Sept", "oct": "Oct", "nov": "Nov", "dec": "Déc",
    "monday": "Lundi", "tuesday": "Mardi", "wednesday": "Mercredi",
    "thursday": "Jeudi", "friday": "Vendredi", "saturday": "Samedi", "sunday": "Dimanche",
    "today": "Aujourd'hui", "yesterday": "Hier", "tomorrow": "Demain",
    "thisWeek": "Cette semaine", "thisMonth": "Ce mois", "thisYear": "Cette année"
  }
};

fs.writeFileSync(path.join(localesDir, 'fr.json'), JSON.stringify(fr, null, 2) + '\n');
console.log('✓ fr.json written');

const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));
let missing = 0;
for (const section of Object.keys(en)) {
  if (!fr[section]) { console.log(`  ✗ Missing section: ${section}`); missing++; continue; }
  for (const key of Object.keys(en[section])) {
    if (typeof en[section][key] === 'object') {
      if (!fr[section][key]) { console.log(`  ✗ Missing nested: ${section}.${key}`); missing++; continue; }
      for (const subkey of Object.keys(en[section][key])) {
        if (fr[section][key][subkey] === undefined) { console.log(`  ✗ Missing: ${section}.${key}.${subkey}`); missing++; }
      }
    } else {
      if (fr[section][key] === undefined) { console.log(`  ✗ Missing: ${section}.${key}`); missing++; }
    }
  }
}
if (missing === 0) console.log('✓ All keys present in fr.json');
else console.log(`✗ ${missing} missing key(s)`);
