const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '..', 'src', 'locales');

const pt = {
  "nav": {
    "core": "Principal",
    "operations": "Operações",
    "administration": "Administração",
    "dashboard": "Painel",
    "projects": "Nossos Projetos",
    "proposals": "Propostas",
    "staff": "Pessoal",
    "allocations": "Alocações",
    "timesheets": "Folhas de horas",
    "absences": "Ausências",
    "financials": "Finanças",
    "timeline": "Cronologia",
    "reports": "Relatórios",
    "import": "Importar",
    "auditLog": "Registo de auditoria",
    "collaboration": "Colaboração",
    "settings": "Configurações",
    "projectOverview": "Visão geral do projeto",
    "help": "Ajuda e FAQ"
  },
  "common": {
    "save": "Guardar",
    "cancel": "Cancelar",
    "delete": "Eliminar",
    "edit": "Editar",
    "create": "Criar",
    "add": "Adicionar",
    "remove": "Remover",
    "close": "Fechar",
    "confirm": "Confirmar",
    "back": "Voltar",
    "next": "Seguinte",
    "search": "Pesquisar",
    "filter": "Filtrar",
    "export": "Exportar",
    "loading": "A carregar...",
    "saving": "A guardar...",
    "deleting": "A eliminar...",
    "noResults": "Sem resultados encontrados",
    "error": "Erro",
    "success": "Sucesso",
    "warning": "Aviso",
    "actions": "Ações",
    "status": "Estado",
    "name": "Nome",
    "email": "E-mail",
    "role": "Função",
    "date": "Data",
    "type": "Tipo",
    "description": "Descrição",
    "notes": "Notas",
    "total": "Total",
    "active": "Ativo",
    "inactive": "Inativo",
    "all": "Todos",
    "yes": "Sim",
    "no": "Não",
    "or": "ou",
    "and": "e",
    "of": "de",
    "to": "a",
    "from": "de",
    "submit": "Submeter",
    "approve": "Aprovar",
    "reject": "Rejeitar",
    "pending": "Pendente",
    "approved": "Aprovado",
    "rejected": "Rejeitado",
    "download": "Descarregar",
    "upload": "Carregar",
    "refresh": "Atualizar",
    "reset": "Repor",
    "selectAll": "Selecionar tudo",
    "deselectAll": "Desselecionar tudo",
    "showing": "A mostrar",
    "items": "itens",
    "page": "Página",
    "previous": "Anterior",
    "rows": "linhas",
    "columns": "Colunas",
    "viewAll": "Ver tudo",
    "learnMore": "Saber mais",
    "required": "Obrigatório",
    "optional": "Opcional",
    "synced": "Sincronizado",
    "upToDate": "Atualizado",
    "syncing": "A sincronizar...",
    "computing": "A calcular...",
    "adding": "A adicionar...",
    "updating": "A atualizar...",
    "project": "Projeto",
    "projects": "projetos",
    "budget": "Orçamento",
    "actual": "Real",
    "remaining": "Restante",
    "over": "Excesso",
    "period": "Período",
    "title": "Título",
    "acronym": "Acrónimo",
    "scheme": "Programa",
    "lead": "Responsável",
    "programme": "Programa",
    "partners": "Parceiros",
    "searchPlaceholder": "Pesquisar por acrónimo ou título...",
    "noProjectsFound": "Nenhum projeto encontrado",
    "tryAdjusting": "Tente ajustar a sua pesquisa.",
    "createFirstProject": "Crie o seu primeiro projeto para começar.",
    "showingCount": "A mostrar {{count}} projeto(s)",
    "deleteProject": "Eliminar projeto",
    "deleteProjectConfirm": "Tem a certeza de que deseja eliminar \"{{name}}\"? Todos os pacotes de trabalho, alocações e folhas de horas associados serão também eliminados.",
    "deleted": "Eliminado",
    "hasBeenRemoved": "{{name}} foi removido.",
    "failedToDelete": "Falha ao eliminar",
    "failedToSave": "Falha ao guardar",
    "suspended": "Suspenso",
    "upcoming": "Próximo",
    "none": "Nenhum",
    "member": "Membro",
    "person": "Pessoa",
    "amount": "Montante",
    "vendor": "Fornecedor",
    "reference": "Referência",
    "category": "Categoria",
    "update": "Atualizar",
    "record": "Registar",
    "invited": "Convidado",
    "account": "Conta",
    "overBudget": "Acima do orçamento",
    "noneSelected": "— Nenhum —",
    "ref": "Ref: {{ref}}",
    "countItems": "{{count}} {{item}}",
    "allCategories": "Todas as categorias",
    "exportPdf": "Exportar PDF"
  },
  "auth": {
    "login": "Entrar",
    "logout": "Sair",
    "signUp": "Registar",
    "signIn": "Iniciar sessão",
    "forgotPassword": "Esqueceu a palavra-passe?",
    "resetPassword": "Repor palavra-passe",
    "setNewPassword": "Definir nova palavra-passe",
    "email": "E-mail",
    "password": "Palavra-passe",
    "confirmPassword": "Confirmar palavra-passe",
    "firstName": "Nome próprio",
    "lastName": "Apelido",
    "rememberMe": "Manter sessão iniciada",
    "createAccount": "Criar a sua conta",
    "alreadyHaveAccount": "Já tem uma conta?",
    "dontHaveAccount": "Não tem conta?",
    "termsAgree": "Ao clicar, confirma que leu e aceita os",
    "termsOfUse": "Termos de utilização",
    "privacyPolicy": "Política de privacidade",
    "startTrial": "Teste gratuito de 14 dias",
    "noPaymentRequired": "Sem necessidade de informação de pagamento",
    "startUsingImmediately": "Comece a usar o GrantLume imediatamente",
    "noInstallation": "Sem instalação",
    "cloudBased": "Na nuvem — funciona no seu navegador",
    "trialAutoEnds": "O período de teste de 14 dias termina automaticamente",
    "noObligations": "Sem obrigações, cancele a qualquer momento",
    "registerFree": "Registar gratuitamente",
    "startFreeTrial": "Comece o seu teste gratuito de 14 dias — sem cartão de crédito",
    "creatingAccount": "A criar conta...",
    "checkYourEmail": "Verifique o seu e-mail",
    "confirmationSent": "Enviámos um link de confirmação para",
    "clickToActivate": "Clique no link para ativar a sua conta e iniciar o seu teste gratuito de 14 dias.",
    "didntReceive": "Não recebeu o e-mail? Verifique a pasta de spam ou aguarde alguns minutos.",
    "resendConfirmation": "Reenviar e-mail de confirmação",
    "goToLogin": "Ir para o início de sessão",
    "passwordStrength": "Força da palavra-passe",
    "weak": "Fraca",
    "fair": "Razoável",
    "good": "Boa",
    "strong": "Forte",
    "passwordsDoNotMatch": "As palavras-passe não coincidem",
    "accountRecovery": "Recuperação de conta",
    "wellHelpYouBack": "Vamos ajudá-lo a recuperar o acesso à sua conta",
    "sendResetLink": "Enviar link",
    "sendingResetLink": "A enviar...",
    "resetLinkSent": "Verifique o seu e-mail",
    "resetLinkSentDesc": "Se existir uma conta com esse e-mail, receberá um link de reposição.",
    "backToLogin": "Voltar ao início de sessão",
    "chooseStrongPassword": "Escolha uma palavra-passe forte e única",
    "newPassword": "Nova palavra-passe",
    "updatePassword": "Atualizar palavra-passe",
    "updatingPassword": "A atualizar...",
    "passwordUpdated": "Palavra-passe atualizada",
    "canNowSignIn": "Pode agora iniciar sessão com a sua nova palavra-passe",
    "securityCheck": "Verificação de segurança",
    "solveToProve": "Resolva isto para provar que é humano",
    "tooManyAttempts": "Demasiadas tentativas falhadas. Tente novamente mais tarde."
  },
  "callback": {
    "verifying": "A verificar...",
    "pleaseWait": "Aguarde enquanto confirmamos a sua conta",
    "emailConfirmed": "E-mail confirmado!",
    "accountVerified": "A sua conta foi verificada com sucesso. Está pronto para configurar a sua organização e começar a gerir as suas subvenções.",
    "whatsNext": "E agora?",
    "step1": "Crie a sua organização",
    "step2": "Adicione o seu primeiro projeto",
    "step3": "Convide os membros da sua equipa",
    "continueToSetup": "Continuar com a configuração",
    "youreAllSet": "Tudo pronto!",
    "verifiedRedirecting": "Verificado! A redirecionar...",
    "verificationFailed": "Falha na verificação",
    "linkExpired": "Não foi possível verificar o seu e-mail. O link pode ter expirado ou já foi utilizado. Por favor tente iniciar sessão."
  },
  "dashboard": {
    "title": "Painel",
    "welcome": "Bem-vindo de volta",
    "overview": "Visão geral",
    "activeProjects": "Projetos ativos",
    "totalStaff": "Pessoal total",
    "pendingTimesheets": "Folhas de horas pendentes",
    "upcomingDeadlines": "Prazos próximos",
    "recentActivity": "Atividade recente",
    "quickActions": "Ações rápidas",
    "budgetOverview": "Visão geral do orçamento",
    "projectStatus": "Estado do projeto",
    "portfolioOverview": "Visão geral do portfólio — {{year}}",
    "kpiProjects": "Projetos",
    "kpiStaff": "Pessoal",
    "kpiTotalBudget": "Orçamento total",
    "kpiPersonMonths": "Pessoa-mês",
    "kpiProposals": "Propostas",
    "kpiCollaborations": "Colaborações",
    "activeCount": "{{count}} ativo(s)",
    "submittedCount": "{{count}} submetido(s)",
    "acrossAllProjects": "em todos os projetos",
    "actualIn": "real em {{year}}",
    "plannedIn": "planeado em {{year}}",
    "projectsEndingSoon": "{{count}} projeto(s) a terminar em breve: {{names}}",
    "staffOverAllocated": "{{count}} membro(s) do pessoal sobrealocado(s) este ano",
    "monthlyAllocations": "Alocações mensais (PM)",
    "projectStatusDistribution": "Distribuição de estados de projeto",
    "noProjectsYet": "Ainda sem projetos",
    "projectsOverview": "Visão geral dos projetos",
    "pmsYear": "PM ({{year}})"
  },
  "projects": {
    "title": "Nossos Projetos",
    "description": "A participação da sua organização em cada projeto",
    "newProject": "Novo projeto",
    "editProject": "Editar projeto",
    "importWithAI": "Importar com IA",
    "projectDetails": "Detalhes do projeto",
    "acronym": "Acrónimo",
    "fullTitle": "Título completo",
    "startDate": "Data de início",
    "endDate": "Data de fim",
    "fundingScheme": "Programa de financiamento",
    "budget": "Orçamento",
    "responsiblePerson": "Pessoa responsável",
    "workPackages": "Pacotes de trabalho",
    "deliverables": "Entregáveis",
    "milestones": "Marcos",
    "personnel": "Pessoal",
    "documents": "Documentos",
    "expenses": "Despesas",
    "noProjects": "Ainda sem projetos",
    "noProjectsDesc": "Crie o seu primeiro projeto para começar.",
    "status": "Estado",
    "active": "Ativo",
    "completed": "Concluído",
    "preparation": "Em preparação",
    "pmRate": "Taxa PM",
    "totalBudget": "Orçamento total",
    "spentBudget": "Gasto",
    "remainingBudget": "Restante",
    "collaboration": "Colaboração",
    "collaborationProjects": "Projetos de colaboração",
    "notFound": "Projeto não encontrado",
    "backToProjects": "Voltar aos projetos",
    "overview": "Visão geral",
    "reporting": "Relatórios",
    "grantNumber": "Número da subvenção",
    "ledByOurOrg": "Liderado pela nossa organização",
    "budgetBreakdown": "Desagregação do orçamento",
    "travel": "Viagens",
    "subcontracting": "Subcontratação",
    "other": "Outros",
    "otherDirectCosts": "Outros custos diretos",
    "indirectCosts": "Custos indiretos",
    "overheadRate": "Taxa de custos gerais",
    "ourPmRate": "A nossa taxa PM",
    "personMonthsPerYear": "Pessoa-mês por ano",
    "totalAcrossYears": "Total em todos os anos",
    "assignedToWPs": "Atribuído aos PTs",
    "ofBudget": "do orçamento",
    "allocated": "Alocado",
    "peopleAllocated": "Pessoas alocadas ao projeto",
    "remaining": "Restante",
    "budgetMinusAllocated": "Orçamento menos alocado",
    "projectBudget": "Orçamento do projeto",
    "pmBudgetDistribution": "Distribuição do orçamento PM",
    "unassigned": "Não atribuído",
    "addWorkPackage": "Adicionar pacote de trabalho",
    "wpNumber": "PT #",
    "wpName": "Nome",
    "wpDescription": "Descrição",
    "startMonth": "Mês de início",
    "endMonth": "Mês de fim",
    "addWP": "Adicionar PT",
    "wpAdded": "Pacote de trabalho adicionado",
    "wpDeleted": "Pacote de trabalho eliminado",
    "wpUpdated": "Pacote de trabalho atualizado.",
    "deleteWP": "Eliminar pacote de trabalho",
    "deleteWPConfirm": "Tem a certeza de que deseja eliminar \"{{name}}\"?",
    "budgetPM": "Orçamento PM",
    "savePmBudgets": "Guardar orçamentos PM",
    "pmBudgetsUpdated": "Orçamentos PM atualizados.",
    "wpPmBudgetsUpdated": "Orçamentos PM dos PT atualizados.",
    "projectDuration": "Duração do projeto: {{months}} meses ({{start}} – {{end}})"
  },
  "expenses": {
    "title": "Despesas",
    "recordExpense": "Registar despesa",
    "editExpense": "Editar despesa",
    "deleteExpense": "Eliminar despesa",
    "deleteExpenseConfirm": "Eliminar \"{{name}}\" ({{amount}})?",
    "expenseRecorded": "Despesa registada",
    "expenseUpdated": "Despesa atualizada",
    "expenseDeleted": "Despesa eliminada",
    "invalidAmount": "Montante inválido",
    "noExpenses": "Sem despesas registadas",
    "noExpensesDesc": "Registe despesas do projeto para acompanhar o consumo do orçamento em viagens, subcontratação e outras categorias de custos.",
    "spent": "Gasto",
    "budgetForCategory": "Orçamento para {{category}}:",
    "afterThisExpense": "Após esta despesa:",
    "remainingAfter": "{{amount}} restante",
    "overBudgetAfter": "{{amount}} acima do orçamento",
    "budgetAlertMessage": "O orçamento de {{category}} está consumido a {{spentPct}}% mas apenas {{timelinePct}}% da duração do projeto decorreu.",
    "descriptionPlaceholder": "Ex. Voo para Bruxelas para reunião do consórcio",
    "vendorPlaceholder": "Ex. TAP, Hotel Bruxelas",
    "referencePlaceholder": "Ex. FAT-2026-001",
    "additionalDetails": "Detalhes adicionais...",
    "vendorPayee": "Fornecedor / Beneficiário",
    "referenceInvoice": "Referência / N.º de fatura",
    "expenseCount": "{{count}} despesa",
    "expenseCountPlural": "{{count}} despesas"
  },
  "deliverables": {
    "title": "Entregáveis",
    "addDeliverable": "Adicionar entregável",
    "editDeliverable": "Editar entregável",
    "deleteDeliverable": "Eliminar entregável",
    "deleteDeliverableConfirm": "Eliminar entregável \"{{name}}\"?",
    "deliverableAdded": "Entregável adicionado",
    "deliverableUpdated": "Entregável atualizado",
    "deliverableDeleted": "Entregável eliminado",
    "noDeliverables": "Sem entregáveis",
    "noDeliverablesDesc": "Adicione entregáveis ao projeto para acompanhar os resultados e prazos.",
    "number": "Número",
    "dueMonth": "Mês de vencimento",
    "workPackage": "Pacote de trabalho",
    "addMilestone": "Adicionar marco",
    "editMilestone": "Editar marco",
    "deleteMilestone": "Eliminar marco",
    "deleteMilestoneConfirm": "Eliminar marco \"{{name}}\"?",
    "milestoneAdded": "Marco adicionado",
    "milestoneUpdated": "Marco atualizado",
    "milestoneDeleted": "Marco eliminado",
    "noMilestones": "Sem marcos",
    "noMilestonesDesc": "Adicione marcos ao projeto para acompanhar as conquistas chave.",
    "verificationMeans": "Meios de verificação"
  },
  "reporting": {
    "title": "Períodos de relatório",
    "addPeriod": "Adicionar período",
    "editPeriod": "Editar período",
    "deletePeriod": "Eliminar período",
    "deletePeriodConfirm": "Eliminar período de relatório #{{number}}?",
    "periodAdded": "Período de relatório adicionado",
    "periodUpdated": "Período de relatório atualizado",
    "periodDeleted": "Período de relatório eliminado",
    "noPeriods": "Sem períodos de relatório",
    "noPeriodsDesc": "Adicione períodos de relatório para acompanhar os prazos de revisão.",
    "periodNumber": "Período #",
    "technicalReportDue": "Relatório técnico a entregar",
    "financialReportDue": "Relatório financeiro a entregar"
  },
  "budgetChart": {
    "title": "Consumo do orçamento",
    "budgeted": "Orçamentado",
    "actual": "Real",
    "percentUsed": "{{percent}}% utilizado",
    "noData": "Sem dados de orçamento disponíveis para este projeto.",
    "timeElapsed": "{{percent}}% do tempo do projeto decorrido",
    "overSpending": "Os gastos estão à frente do calendário",
    "underSpending": "Os gastos estão dentro do previsto",
    "categories": {
      "personnel": "Pessoal",
      "travel": "Viagens",
      "subcontracting": "Subcontratação",
      "other": "Outros",
      "indirect": "Indireto"
    }
  },
  "staff": {
    "title": "Pessoal",
    "addPerson": "Adicionar nova pessoa",
    "editPerson": "Editar pessoa",
    "fullName": "Nome completo",
    "department": "Departamento",
    "role": "Função",
    "employmentType": "Tipo de emprego",
    "fte": "ETC",
    "startDate": "Data de início",
    "endDate": "Data de fim",
    "salary": "Salário anual",
    "vacationDays": "Dias de férias",
    "country": "País",
    "isActive": "Ativo",
    "noStaff": "Ainda sem pessoal",
    "noStaffDesc": "Adicione o seu primeiro membro de equipa para começar.",
    "inviteToSystem": "Convidar para GrantLume",
    "accountStatus": "Estado da conta",
    "sendInvitation": "Enviar convite",
    "resendInvitation": "Reenviar convite",
    "personCreated": "Pessoa criada",
    "personUpdated": "Pessoa atualizada",
    "personDeleted": "Pessoa eliminada",
    "deletePerson": "Eliminar pessoa",
    "deletePersonConfirm": "Tem a certeza de que deseja eliminar \"{{name}}\"?",
    "searchPlaceholder": "Pesquisar pessoal...",
    "leaveBalance": "Saldo de férias",
    "leaveUsed": "{{used}} / {{total}} dias utilizados",
    "overheadRate": "Taxa de custos gerais",
    "phone": "Telefone",
    "avatar": "Avatar",
    "uploadAvatar": "Carregar avatar",
    "removeAvatar": "Remover avatar",
    "personalInfo": "Informações pessoais",
    "employmentDetails": "Detalhes de emprego",
    "financialInfo": "Informações financeiras",
    "invitationSent": "Convite enviado",
    "invitationResent": "Convite reenviado",
    "invitingUser": "A convidar...",
    "systemRole": "Função no sistema",
    "projectsInvolved": "Projetos envolvidos"
  },
  "allocations": {
    "title": "Alocações",
    "description": "Gerir alocações de pessoa-mês entre projetos",
    "personMonth": "Pessoa-mês",
    "personMonths": "Pessoa-meses",
    "pm": "PM",
    "capacity": "Capacidade",
    "overAllocated": "Sobrealocado",
    "unsavedChanges": "Alterações não guardadas",
    "pmBudgets": "Orçamentos PM",
    "bulkFill": "Preenchimento em massa",
    "addRow": "Adicionar linha",
    "undo": "Desfazer",
    "redo": "Refazer",
    "allocationGrid": "Grelha de alocações",
    "personnelOverview": "Visão geral do pessoal",
    "projectOverview": "Visão geral do projeto",
    "periodLocks": "Bloqueios de período",
    "saved": "Alocações guardadas",
    "selectPerson": "Selecionar pessoa",
    "selectProject": "Selecionar projeto",
    "selectWorkPackage": "Selecionar pacote de trabalho"
  },
  "timesheets": {
    "title": "Folhas de horas",
    "myTimesheet": "A minha folha de horas",
    "allTimesheets": "Todas as folhas de horas",
    "submitTimesheet": "Submeter folha de horas",
    "approveTimesheets": "Aprovar folhas de horas",
    "hours": "Horas",
    "totalHours": "Total de horas",
    "period": "Período",
    "submitted": "Submetido",
    "draft": "Rascunho",
    "noEntries": "Ainda sem registos",
    "noEntriesDesc": "Comece a registar as suas horas para este período.",
    "weeklyView": "Vista semanal",
    "monthlyView": "Vista mensal",
    "timesheetSubmitted": "Folha de horas submetida",
    "timesheetApproved": "Folha de horas aprovada",
    "timesheetRejected": "Folha de horas rejeitada",
    "timesheetSaved": "Folha de horas guardada",
    "submitConfirm": "Submeter esta folha de horas? Após a submissão, não poderá ser editada até ser revista.",
    "workingDay": "Dia útil",
    "weekend": "Fim de semana",
    "holiday": "Feriado",
    "selectMonth": "Selecionar mês",
    "noTimesheetData": "Sem dados de folhas de horas",
    "noTimesheetDataDesc": "Nenhum registo encontrado para este período."
  },
  "absences": {
    "title": "Ausências",
    "description": "Acompanhar ausências e férias do pessoal",
    "newAbsence": "Nova ausência",
    "editAbsence": "Editar ausência",
    "deleteAbsence": "Eliminar ausência",
    "deleteAbsenceConfirm": "Eliminar este registo de ausência?",
    "absenceType": "Tipo de ausência",
    "vacation": "Férias",
    "sickLeave": "Baixa médica",
    "publicHoliday": "Feriado",
    "training": "Formação",
    "conference": "Conferência",
    "other": "Outro",
    "startDate": "Data de início",
    "endDate": "Data de fim",
    "days": "Dias",
    "halfDay": "Meio dia",
    "reason": "Motivo",
    "noAbsences": "Sem ausências registadas",
    "noAbsencesDesc": "Registe ausências para acompanhar a disponibilidade da equipa.",
    "approvers": "Aprovadores",
    "myAbsences": "As minhas ausências",
    "teamAbsences": "Ausências da equipa",
    "timeline": "Cronologia",
    "listView": "Vista de lista",
    "absenceCreated": "Ausência registada",
    "absenceUpdated": "Ausência atualizada",
    "absenceDeleted": "Ausência eliminada",
    "absenceApproved": "Ausência aprovada",
    "absenceRejected": "Ausência rejeitada",
    "substitute": "Substituto",
    "selectPerson": "Selecionar pessoa",
    "daysCount": "{{count}} dia(s)"
  },
  "financials": {
    "title": "Finanças",
    "description": "Acompanhamento orçamento vs. real para {{year}}",
    "budgetOverview": "Visão geral do orçamento",
    "enterActuals": "Introduzir reais",
    "expenses": "Despesas",
    "category": "Categoria",
    "amount": "Montante",
    "personnelBudget": "Pessoal",
    "travelBudget": "Viagens",
    "subcontractingBudget": "Subcontratação",
    "otherBudget": "Outros diretos",
    "indirectCosts": "Custos indiretos",
    "totalBudget": "Orçamento total",
    "spent": "Gasto",
    "remaining": "Restante",
    "utilization": "Utilização",
    "syncBudgets": "Sincronizar orçamentos dos projetos",
    "computePersonnel": "Calcular reais de pessoal",
    "syncExpenses": "Sincronizar reais de despesas",
    "noFinancialData": "Sem dados financeiros",
    "noFinancialDataDesc": "Adicione projetos e entradas de orçamento para ver a visão geral orçamento vs. real.",
    "budgetRowsUpToDate": "Todas as linhas de orçamento estão atualizadas e sincronizadas com os dados do projeto.",
    "budgetRowsSynced": "Linhas de orçamento: {{details}}.",
    "created": "criado",
    "updated": "atualizado",
    "personnelUpToDate": "Os reais de pessoal já correspondem aos dados de alocação.",
    "personnelSynced": "{{count}} real(is) de pessoal atualizado(s) a partir de dados de alocação.",
    "expensesUpToDate": "Os reais não pessoal já correspondem aos registos de despesas.",
    "expensesSynced": "{{count}} real(is) de orçamento atualizado(s) a partir de registos de despesas.",
    "under80": "Abaixo de 80%",
    "between80and100": "80–100%",
    "overBudget": "Acima do orçamento",
    "grandTotal": "TOTAL",
    "actualsSaved": "Reais guardados"
  },
  "proposals": {
    "title": "Propostas",
    "description": "Acompanhar candidaturas a subvenções e converter as aprovadas em projetos",
    "newProposal": "Nova proposta",
    "editProposal": "Editar proposta",
    "deleteProposal": "Eliminar proposta",
    "deleteProposalConfirm": "Tem a certeza de que deseja eliminar \"{{name}}\"? Esta ação não pode ser desfeita.",
    "proposalCreated": "Proposta criada",
    "proposalUpdated": "Proposta atualizada",
    "proposalDeleted": "Proposta eliminada",
    "projectName": "Nome do projeto",
    "callIdentifier": "Identificador do concurso",
    "fundingScheme": "Programa de financiamento",
    "submissionDeadline": "Prazo de submissão",
    "expectedDecision": "Decisão esperada",
    "approxDecisionDate": "Data de decisão aproximada",
    "ourPms": "Os nossos PMs",
    "inPreparation": "Em preparação",
    "submitted": "Submetido",
    "granted": "Aprovado",
    "rejected": "Rejeitado",
    "convertToProject": "Converter em projeto",
    "convertToProjectConfirm": "Isto criará um novo projeto a partir de \"{{name}}\" com os dados orçamentários da proposta. Poderá editar os detalhes do projeto depois. Continuar?",
    "projectCreated": "Projeto criado!",
    "projectCreatedDesc": "A redirecionar para o novo projeto...",
    "converting": "A converter...",
    "createProject": "Criar projeto",
    "pipeline": "Pipeline",
    "noProposals": "Ainda sem propostas",
    "noProposalsDesc": "Acompanhe as suas propostas de subvenção da submissão à decisão.",
    "addFirstProposal": "Adicione a sua primeira proposta",
    "allProposals": "Todas as propostas",
    "filteredProposals": "Propostas {{status}}",
    "budgetBreakdown": "Desagregação do orçamento",
    "personnelBudget": "Orçamento de pessoal",
    "travelBudget": "Orçamento de viagens",
    "subcontractingBudget": "Orçamento de subcontratação",
    "otherBudget": "Outro orçamento",
    "totalBudget": "Orçamento total",
    "responsiblePerson": "Pessoa responsável",
    "updateProposal": "Atualizar proposta",
    "createProposal": "Criar proposta",
    "enterDetails": "Introduza os detalhes da sua candidatura a subvenção.",
    "updateDetails": "Atualize os detalhes da proposta.",
    "searchEuCalls": "Pesquisar concursos UE ou escrever identificador...",
    "searchEuCallsHint": "Comece a escrever para pesquisar concursos abertos de EU Funding & Tenders, ou introduza qualquer identificador",
    "selectFundingScheme": "Selecionar ou escrever um programa de financiamento...",
    "noMatchingSchemes": "Sem programas correspondentes — escreva um personalizado",
    "goToProject": "Ir para o projeto"
  },
  "settings": {
    "title": "Configurações",
    "description": "Configurações e definições da organização",
    "organisation": "Organização",
    "orgName": "Nome da organização",
    "currency": "Moeda",
    "workingHours": "Horas de trabalho por dia",
    "departments": "Departamentos",
    "users": "Utilizadores",
    "members": "Membros da organização",
    "addMember": "Adicionar membro",
    "removeMember": "Remover membro",
    "rolePermissions": "Permissões de funções",
    "fundingSchemes": "Programas de financiamento",
    "holidays": "Feriados",
    "periodLocking": "Bloqueio de períodos",
    "language": "Idioma",
    "selectLanguage": "Selecionar idioma",
    "languageDesc": "Escolha o seu idioma de interface preferido. Esta definição é guardada no seu perfil.",
    "general": "Geral",
    "dangerZone": "Zona de perigo",
    "absenceApprovers": "Aprovadores de ausências",
    "absenceTypes": "Tipos de ausências",
    "rolePermDesc": "Configure o que cada função pode ver e fazer. Os administradores têm sempre acesso total. Os participantes externos só podem aceder aos projetos para os quais são convidados.",
    "moduleVisibility": "Visibilidade dos módulos",
    "whichSections": "Que secções aparecem na barra lateral",
    "sensitiveData": "Dados sensíveis",
    "accessConfidential": "Acesso a informações confidenciais",
    "actionsLabel": "Ações",
    "whatRoleCanDo": "O que esta função pode criar, editar ou gerir",
    "adminNote": "A função de administrador tem sempre acesso total a todos os módulos e dados. As alterações abaixo aplicam-se apenas aos utilizadores <strong>{{role}}</strong>.",
    "resetToDefaults": "Repor predefinições",
    "saveChanges": "Guardar alterações",
    "resetConfirm": "Repor permissões de \"{{role}}\"?\n\nIsto descartará todas as personalizações para esta função.",
    "permissionsSaved": "Permissões de função atualizadas. Os utilizadores verão as alterações no próximo início de sessão.",
    "settingsSaved": "Configurações guardadas",
    "memberInvited": "Membro convidado",
    "memberRemoved": "Membro removido",
    "memberRoleUpdated": "Função do membro atualizada",
    "schemeAdded": "Programa de financiamento adicionado",
    "schemeDeleted": "Programa de financiamento eliminado",
    "holidayAdded": "Feriado adicionado",
    "holidayDeleted": "Feriado eliminado",
    "departmentAdded": "Departamento adicionado",
    "departmentDeleted": "Departamento eliminado",
    "approverAdded": "Aprovador adicionado",
    "approverRemoved": "Aprovador removido",
    "periodLocked": "Período bloqueado",
    "periodUnlocked": "Período desbloqueado"
  },
  "profile": {
    "title": "As minhas definições",
    "description": "Gerir o seu perfil pessoal, palavra-passe e preferências de notificações por e-mail",
    "displayName": "Nome de exibição",
    "changePassword": "Alterar palavra-passe",
    "currentPassword": "Palavra-passe atual",
    "newPassword": "Nova palavra-passe",
    "confirmPassword": "Confirmar palavra-passe",
    "emailNotifications": "Notificações por e-mail",
    "managePreferences": "Gerir quais notificações por e-mail recebe.",
    "profileSection": "Perfil",
    "accountInfo": "As suas informações de conta",
    "organisation": "Organização",
    "passwordTooShort": "A palavra-passe deve ter pelo menos 6 caracteres.",
    "passwordMismatch": "As palavras-passe não coincidem",
    "passwordUpdated": "Palavra-passe atualizada com sucesso",
    "profileSaved": "Perfil guardado",
    "saveProfile": "Guardar perfil",
    "updatePassword": "Alterar palavra-passe",
    "updatingPassword": "A atualizar...",
    "minCharacters": "Mín. 6 caracteres",
    "reEnterPassword": "Reintroduza a palavra-passe",
    "displayNamePlaceholder": "O seu nome de exibição",
    "dbMigrationNote": "As preferências de notificação por e-mail requerem uma migração de base de dados. Execute <code>supabase/add_user_preferences.sql</code> no seu editor SQL do Supabase. Até lá, todas as notificações estão ativadas por predefinição.",
    "prefsNotAvailable": "Tabela de preferências ainda não disponível. Execute primeiro a migração SQL.",
    "couldNotSave": "Não foi possível guardar — a tabela de preferências pode não estar configurada.",
    "couldNotSavePref": "Não foi possível guardar a preferência — a tabela pode não estar configurada.",
    "languageChanged": "Idioma da interface alterado para {{language}}"
  },
  "reports": {
    "title": "Relatórios",
    "generateReport": "Gerar relatório",
    "projectSummary": "Resumo do projeto",
    "financialReport": "Relatório financeiro",
    "timesheetReport": "Relatório de folhas de horas",
    "staffAllocations": "Alocações de pessoal",
    "absenceSummary": "Resumo de ausências",
    "reportGenerated": "Relatório gerado",
    "generating": "A gerar..."
  },
  "guests": {
    "title": "Acesso de convidados",
    "inviteGuest": "Convidar convidado",
    "guestEmail": "E-mail do convidado",
    "projectAccess": "Acesso ao projeto",
    "accessLevel": "Nível de acesso",
    "revokeAccess": "Revogar acesso"
  },
  "audit": {
    "title": "Registo de auditoria",
    "action": "Ação",
    "entity": "Entidade",
    "user": "Utilizador",
    "timestamp": "Carimbo temporal",
    "details": "Detalhes"
  },
  "import": {
    "title": "Importar",
    "importData": "Importar dados",
    "selectFile": "Selecionar ficheiro",
    "dragAndDrop": "Arraste e solte um ficheiro aqui",
    "supportedFormats": "Formatos suportados: CSV, XLSX",
    "processing": "A processar...",
    "mapping": "Mapear colunas",
    "preview": "Pré-visualização",
    "importComplete": "Importação concluída",
    "importFailed": "Falha na importação",
    "rowsImported": "{{count}} linhas importadas",
    "downloadTemplate": "Descarregar modelo",
    "step1Upload": "Carregar",
    "step2Processing": "A processar",
    "step3Map": "Mapear",
    "step4Preview": "Pré-visualizar"
  },
  "documents": {
    "title": "Documentos",
    "uploadDocument": "Carregar documento",
    "deleteDocument": "Eliminar documento",
    "deleteDocumentConfirm": "Eliminar \"{{name}}\"?",
    "documentUploaded": "Documento carregado",
    "documentDeleted": "Documento eliminado",
    "noDocuments": "Sem documentos",
    "noDocumentsDesc": "Carregue documentos do projeto para manter tudo organizado.",
    "fileName": "Nome do ficheiro",
    "fileSize": "Tamanho",
    "uploadedBy": "Carregado por",
    "uploadedAt": "Carregado em"
  },
  "collaboration": {
    "title": "Projetos de colaboração",
    "description": "Gerir projetos de colaboração com múltiplos parceiros",
    "newProject": "Novo projeto de colaboração",
    "editProject": "Editar projeto",
    "deleteProject": "Eliminar projeto",
    "projectCreated": "Projeto de colaboração criado",
    "projectUpdated": "Projeto de colaboração atualizado",
    "projectDeleted": "Projeto de colaboração eliminado",
    "partners": "Parceiros",
    "addPartner": "Adicionar parceiro",
    "editPartner": "Editar parceiro",
    "deletePartner": "Eliminar parceiro",
    "partnerAdded": "Parceiro adicionado",
    "partnerUpdated": "Parceiro atualizado",
    "partnerDeleted": "Parceiro eliminado",
    "contacts": "Contactos",
    "addContact": "Adicionar contacto",
    "editContact": "Editar contacto",
    "deleteContact": "Eliminar contacto",
    "contactAdded": "Contacto adicionado",
    "contactUpdated": "Contacto atualizado",
    "contactDeleted": "Contacto eliminado",
    "allocations": "Alocações",
    "tasks": "Tarefas",
    "noProjects": "Ainda sem projetos de colaboração",
    "noProjectsDesc": "Crie um projeto de colaboração para gerir trabalho com múltiplos parceiros.",
    "totalBudget": "Orçamento total",
    "ourShare": "A nossa parte",
    "setup": "Configuração"
  },
  "onboarding": {
    "title": "Bem-vindo ao GrantLume",
    "createOrg": "Crie a sua organização",
    "orgNameLabel": "Nome da organização",
    "currencyLabel": "Moeda predefinida",
    "letsGo": "Vamos!",
    "settingUp": "A configurar..."
  },
  "notifications": {
    "title": "Notificações",
    "markAllRead": "Marcar tudo como lido",
    "noNotifications": "Sem notificações",
    "clearRead": "Limpar lidas"
  },
  "topbar": {
    "mySettings": "As minhas definições",
    "signOut": "Sair",
    "darkMode": "Alternar modo escuro",
    "year": "Ano",
    "trialDaysRemaining": "Teste: {{days}} dias restantes",
    "member": "Membro"
  },
  "landing": {
    "hero": "A plataforma moderna de gestão de subvenções",
    "heroSub": "Otimize a gestão dos seus projetos financiados pela UE e fundos públicos com ferramentas poderosas para alocações, folhas de horas, finanças e relatórios.",
    "getStarted": "Começar gratuitamente",
    "viewDemo": "Ver demonstração",
    "trustedBy": "Confiança de organizações de investigação em toda a Europa"
  },
  "empty": {
    "noData": "Sem dados disponíveis",
    "getStarted": "Comece por criar o seu primeiro item."
  },
  "validation": {
    "required": "Este campo é obrigatório",
    "invalidEmail": "Introduza um endereço de e-mail válido",
    "minLength": "Deve ter pelo menos {{min}} caracteres",
    "maxLength": "Deve ter no máximo {{max}} caracteres",
    "passwordMinLength": "A palavra-passe deve ter pelo menos 8 caracteres",
    "projectNameRequired": "O nome do projeto é obrigatório"
  },
  "time": {
    "jan": "Jan", "feb": "Fev", "mar": "Mar", "apr": "Abr",
    "may": "Mai", "jun": "Jun", "jul": "Jul", "aug": "Ago",
    "sep": "Set", "oct": "Out", "nov": "Nov", "dec": "Dez",
    "monday": "Segunda", "tuesday": "Terça", "wednesday": "Quarta",
    "thursday": "Quinta", "friday": "Sexta", "saturday": "Sábado", "sunday": "Domingo",
    "today": "Hoje", "yesterday": "Ontem", "tomorrow": "Amanhã",
    "thisWeek": "Esta semana", "thisMonth": "Este mês", "thisYear": "Este ano"
  }
};

fs.writeFileSync(path.join(localesDir, 'pt.json'), JSON.stringify(pt, null, 2) + '\n');
console.log('✓ pt.json written');

const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));
let missing = 0;
for (const section of Object.keys(en)) {
  if (!pt[section]) { console.log(`  ✗ Missing section: ${section}`); missing++; continue; }
  for (const key of Object.keys(en[section])) {
    if (typeof en[section][key] === 'object') {
      if (!pt[section][key]) { console.log(`  ✗ Missing nested: ${section}.${key}`); missing++; continue; }
      for (const subkey of Object.keys(en[section][key])) {
        if (pt[section][key][subkey] === undefined) { console.log(`  ✗ Missing: ${section}.${key}.${subkey}`); missing++; }
      }
    } else {
      if (pt[section][key] === undefined) { console.log(`  ✗ Missing: ${section}.${key}`); missing++; }
    }
  }
}
if (missing === 0) console.log('✓ All keys present in pt.json');
else console.log(`✗ ${missing} missing key(s)`);
